/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.verizon.thingspace.DateTimeHelper;
import io.apimatic.coreinterfaces.http.Context;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * This is a model class for MdmErrorResponseException type.
 */
public class MdmErrorResponseException extends ApiException {
    private static final long serialVersionUID = -3829767007685425585L;
    private String error;
    private String description;
    private UUID uuid;
    private LocalDateTime timestamp;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public MdmErrorResponseException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * The short summary of the error
     * @return Returns the String
     */
    @JsonGetter("error")
    public String getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * The short summary of the error
     * @param error Value for String
     */
    @JsonSetter("error")
    private void setError(String error) {
        this.error = error;
    }

    /**
     * Getter for Description.
     * The detailed description of the error
     * @return Returns the String
     */
    @JsonGetter("description")
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for Description.
     * The detailed description of the error
     * @param description Value for String
     */
    @JsonSetter("description")
    private void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for Uuid.
     * The unique identifier of the request for tracing
     * @return Returns the UUID
     */
    @JsonGetter("uuid")
    public UUID getUuid() {
        return this.uuid;
    }

    /**
     * Setter for Uuid.
     * The unique identifier of the request for tracing
     * @param uuid Value for UUID
     */
    @JsonSetter("uuid")
    private void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    /**
     * Getter for Timestamp.
     * The timestamp of when the error occurred
     * @return Returns the LocalDateTime
     */
    @JsonGetter("timestamp")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    /**
     * Setter for Timestamp.
     * The timestamp of when the error occurred
     * @param timestamp Value for LocalDateTime
     */
    @JsonSetter("timestamp")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    private void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Converts this MdmErrorResponseException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MdmErrorResponseException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", error=" + error + ", description=" + description + ", uuid="
                + uuid + ", timestamp=" + timestamp + "]";
    }
}
