/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.thingspace.models.containers.AdvisoryItem;
import java.util.List;

/**
 * This is a model class for AdvisoryContent type.
 */
public class AdvisoryContent {
    private List<AdvisoryItem> advisory;

    /**
     * Default constructor.
     */
    public AdvisoryContent() {
    }

    /**
     * Initialization constructor.
     * @param  advisory  List of AdvisoryItem value for advisory.
     */
    @JsonCreator
    public AdvisoryContent(
            @JsonProperty("advisory") List<AdvisoryItem> advisory) {
        this.advisory = advisory;
    }

    /**
     * Getter for Advisory.
     * List of typical ITIS warnings.
     * @return Returns the List of AdvisoryItem
     */
    @JsonGetter("advisory")
    public List<AdvisoryItem> getAdvisory() {
        return advisory;
    }

    /**
     * Setter for Advisory.
     * List of typical ITIS warnings.
     * @param advisory Value for List of AdvisoryItem
     */
    @JsonSetter("advisory")
    public void setAdvisory(List<AdvisoryItem> advisory) {
        this.advisory = advisory;
    }

    /**
     * Converts this AdvisoryContent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AdvisoryContent [" + "advisory=" + advisory + "]";
    }

    /**
     * Builds a new {@link AdvisoryContent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AdvisoryContent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(advisory);
        return builder;
    }

    /**
     * Class to build instances of {@link AdvisoryContent}.
     */
    public static class Builder {
        private List<AdvisoryItem> advisory;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  advisory  List of AdvisoryItem value for advisory.
         */
        public Builder(List<AdvisoryItem> advisory) {
            this.advisory = advisory;
        }

        /**
         * Setter for advisory.
         * @param  advisory  List of AdvisoryItem value for advisory.
         * @return Builder
         */
        public Builder advisory(List<AdvisoryItem> advisory) {
            this.advisory = advisory;
            return this;
        }

        /**
         * Builds a new {@link AdvisoryContent} object using the set fields.
         * @return {@link AdvisoryContent}
         */
        public AdvisoryContent build() {
            return new AdvisoryContent(advisory);
        }
    }
}
