/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.thingspace.models.containers.DevicesRequestFilter;

/**
 * This is a model class for DevicesRequest type.
 */
public class DevicesRequest {
    private String vendorId;
    private DevicesRequestFilter filter;

    /**
     * Default constructor.
     */
    public DevicesRequest() {
    }

    /**
     * Initialization constructor.
     * @param  vendorId  String value for vendorId.
     * @param  filter  DevicesRequestFilter value for filter.
     */
    public DevicesRequest(
            String vendorId,
            DevicesRequestFilter filter) {
        this.vendorId = vendorId;
        this.filter = filter;
    }

    /**
     * Getter for VendorId.
     * The ID the vendor wants its devices to be registered under. E.g. Verizon, GM, Ford, etc.
     * @return Returns the String
     */
    @JsonGetter("VendorId")
    public String getVendorId() {
        return vendorId;
    }

    /**
     * Setter for VendorId.
     * The ID the vendor wants its devices to be registered under. E.g. Verizon, GM, Ford, etc.
     * @param vendorId Value for String
     */
    @JsonSetter("VendorId")
    public void setVendorId(String vendorId) {
        this.vendorId = vendorId;
    }

    /**
     * Getter for Filter.
     * Devices filter criteria or pagination token
     * @return Returns the DevicesRequestFilter
     */
    @JsonGetter("Filter")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DevicesRequestFilter getFilter() {
        return filter;
    }

    /**
     * Setter for Filter.
     * Devices filter criteria or pagination token
     * @param filter Value for DevicesRequestFilter
     */
    @JsonSetter("Filter")
    public void setFilter(DevicesRequestFilter filter) {
        this.filter = filter;
    }

    /**
     * Converts this DevicesRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DevicesRequest [" + "vendorId=" + vendorId + ", filter=" + filter + "]";
    }

    /**
     * Builds a new {@link DevicesRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DevicesRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(vendorId)
                .filter(getFilter());
        return builder;
    }

    /**
     * Class to build instances of {@link DevicesRequest}.
     */
    public static class Builder {
        private String vendorId;
        private DevicesRequestFilter filter;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  vendorId  String value for vendorId.
         */
        public Builder(String vendorId) {
            this.vendorId = vendorId;
        }

        /**
         * Setter for vendorId.
         * @param  vendorId  String value for vendorId.
         * @return Builder
         */
        public Builder vendorId(String vendorId) {
            this.vendorId = vendorId;
            return this;
        }

        /**
         * Setter for filter.
         * @param  filter  DevicesRequestFilter value for filter.
         * @return Builder
         */
        public Builder filter(DevicesRequestFilter filter) {
            this.filter = filter;
            return this;
        }

        /**
         * Builds a new {@link DevicesRequest} object using the set fields.
         * @return {@link DevicesRequest}
         */
        public DevicesRequest build() {
            return new DevicesRequest(vendorId, filter);
        }
    }
}
