/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for DevicesFilter type.
 */
public class DevicesFilter {
    private EtxClientTypeEnum clientType;
    private ClientSubtypeEnum clientSubtype;
    private String mecId;
    private Integer pageSize;

    /**
     * Default constructor.
     */
    public DevicesFilter() {
    }

    /**
     * Initialization constructor.
     * @param  clientType  EtxClientTypeEnum value for clientType.
     * @param  clientSubtype  ClientSubtypeEnum value for clientSubtype.
     * @param  mecId  String value for mecId.
     * @param  pageSize  Integer value for pageSize.
     */
    public DevicesFilter(
            EtxClientTypeEnum clientType,
            ClientSubtypeEnum clientSubtype,
            String mecId,
            Integer pageSize) {
        this.clientType = clientType;
        this.clientSubtype = clientSubtype;
        this.mecId = mecId;
        this.pageSize = pageSize;
    }

    /**
     * Getter for ClientType.
     * The type of the client that is to be registered. This is one of the major traffic participant
     * groups considered in V2X communication. The system uses this value to define which topics the
     * client will be able to publish and subscribe to. Values: - **Vehicle** - Vehicle with an
     * enclosure around the passengers. (Subtypes: Motorcycle, PassengerCar, Truck, Bus,
     * EmergencyVehicle, SchoolBus, MaintenanceVehicle) - **VulnerableRoadUser** - Traffic
     * participants without a protecting enclosure. (Subtypes: Bicycle, Pedestrian, Scooter) -
     * **TrafficLightController** - A Traffic light controller system. (Subtypes: NA) -
     * **InfrastructureSensor** - Sensors that are deployed in the infrastructure. (Subtypes:
     * RoadSideUnit, Camera, Lidar, Radar, InductiveLoop, MagneticSensor) - **OnboardSensor** -
     * Sensors that are onboard on a vehicle(Subtypes: Camera, Lidar, Radar) - **Software** - A
     * software system or application. (Subtypes: Platform, Application, NA)
     * @return Returns the EtxClientTypeEnum
     */
    @JsonGetter("ClientType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EtxClientTypeEnum getClientType() {
        return clientType;
    }

    /**
     * Setter for ClientType.
     * The type of the client that is to be registered. This is one of the major traffic participant
     * groups considered in V2X communication. The system uses this value to define which topics the
     * client will be able to publish and subscribe to. Values: - **Vehicle** - Vehicle with an
     * enclosure around the passengers. (Subtypes: Motorcycle, PassengerCar, Truck, Bus,
     * EmergencyVehicle, SchoolBus, MaintenanceVehicle) - **VulnerableRoadUser** - Traffic
     * participants without a protecting enclosure. (Subtypes: Bicycle, Pedestrian, Scooter) -
     * **TrafficLightController** - A Traffic light controller system. (Subtypes: NA) -
     * **InfrastructureSensor** - Sensors that are deployed in the infrastructure. (Subtypes:
     * RoadSideUnit, Camera, Lidar, Radar, InductiveLoop, MagneticSensor) - **OnboardSensor** -
     * Sensors that are onboard on a vehicle(Subtypes: Camera, Lidar, Radar) - **Software** - A
     * software system or application. (Subtypes: Platform, Application, NA)
     * @param clientType Value for EtxClientTypeEnum
     */
    @JsonSetter("ClientType")
    public void setClientType(EtxClientTypeEnum clientType) {
        this.clientType = clientType;
    }

    /**
     * Getter for ClientSubtype.
     * The subtype or subgroup of the client type. This further specifies the client type. For
     * example it will specify if the client is a passenger car or a truck. See the ClientType
     * description for the supported Subtypes for each client type.
     * @return Returns the ClientSubtypeEnum
     */
    @JsonGetter("ClientSubtype")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ClientSubtypeEnum getClientSubtype() {
        return clientSubtype;
    }

    /**
     * Setter for ClientSubtype.
     * The subtype or subgroup of the client type. This further specifies the client type. For
     * example it will specify if the client is a passenger car or a truck. See the ClientType
     * description for the supported Subtypes for each client type.
     * @param clientSubtype Value for ClientSubtypeEnum
     */
    @JsonSetter("ClientSubtype")
    public void setClientSubtype(ClientSubtypeEnum clientSubtype) {
        this.clientSubtype = clientSubtype;
    }

    /**
     * Getter for MecId.
     * The unique identifier for a Multi-access Edge Computing (MEC) location in the ETX system.
     * This ID is used to reference and manage MEC locations for registration, update, retrieval,
     * and deletion operations.
     * @return Returns the String
     */
    @JsonGetter("MecId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMecId() {
        return mecId;
    }

    /**
     * Setter for MecId.
     * The unique identifier for a Multi-access Edge Computing (MEC) location in the ETX system.
     * This ID is used to reference and manage MEC locations for registration, update, retrieval,
     * and deletion operations.
     * @param mecId Value for String
     */
    @JsonSetter("MecId")
    public void setMecId(String mecId) {
        this.mecId = mecId;
    }

    /**
     * Getter for PageSize.
     * Number of devices to return per page. If not provided, the server default is used.
     * @return Returns the Integer
     */
    @JsonGetter("PageSize")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * Setter for PageSize.
     * Number of devices to return per page. If not provided, the server default is used.
     * @param pageSize Value for Integer
     */
    @JsonSetter("PageSize")
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Converts this DevicesFilter into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DevicesFilter [" + "clientType=" + clientType + ", clientSubtype=" + clientSubtype
                + ", mecId=" + mecId + ", pageSize=" + pageSize + "]";
    }

    /**
     * Builds a new {@link DevicesFilter.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DevicesFilter.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .clientType(getClientType())
                .clientSubtype(getClientSubtype())
                .mecId(getMecId())
                .pageSize(getPageSize());
        return builder;
    }

    /**
     * Class to build instances of {@link DevicesFilter}.
     */
    public static class Builder {
        private EtxClientTypeEnum clientType;
        private ClientSubtypeEnum clientSubtype;
        private String mecId;
        private Integer pageSize;



        /**
         * Setter for clientType.
         * @param  clientType  EtxClientTypeEnum value for clientType.
         * @return Builder
         */
        public Builder clientType(EtxClientTypeEnum clientType) {
            this.clientType = clientType;
            return this;
        }

        /**
         * Setter for clientSubtype.
         * @param  clientSubtype  ClientSubtypeEnum value for clientSubtype.
         * @return Builder
         */
        public Builder clientSubtype(ClientSubtypeEnum clientSubtype) {
            this.clientSubtype = clientSubtype;
            return this;
        }

        /**
         * Setter for mecId.
         * @param  mecId  String value for mecId.
         * @return Builder
         */
        public Builder mecId(String mecId) {
            this.mecId = mecId;
            return this;
        }

        /**
         * Setter for pageSize.
         * @param  pageSize  Integer value for pageSize.
         * @return Builder
         */
        public Builder pageSize(Integer pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /**
         * Builds a new {@link DevicesFilter} object using the set fields.
         * @return {@link DevicesFilter}
         */
        public DevicesFilter build() {
            return new DevicesFilter(clientType, clientSubtype, mecId, pageSize);
        }
    }
}
