/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import java.util.UUID;

/**
 * This is a model class for DevicesResponse type.
 */
public class DevicesResponse {
    private UUID deviceID;
    private EtxClientTypeEnum clientType;
    private ClientSubtypeEnum clientSubtype;
    private List<String> mecIds;

    /**
     * Default constructor.
     */
    public DevicesResponse() {
    }

    /**
     * Initialization constructor.
     * @param  deviceID  UUID value for deviceID.
     * @param  clientType  EtxClientTypeEnum value for clientType.
     * @param  clientSubtype  ClientSubtypeEnum value for clientSubtype.
     * @param  mecIds  List of String value for mecIds.
     */
    public DevicesResponse(
            UUID deviceID,
            EtxClientTypeEnum clientType,
            ClientSubtypeEnum clientSubtype,
            List<String> mecIds) {
        this.deviceID = deviceID;
        this.clientType = clientType;
        this.clientSubtype = clientSubtype;
        this.mecIds = mecIds;
    }

    /**
     * Getter for DeviceID.
     * The generated ID (UUID v4) for the device. It can be used as: - the MQTT Client ID when
     * connecting to the Message Exchange system - a parameter when asking for the connection
     * endpoint - a parameter when finishing the device registration - a parameter when
     * unregistering the device
     * @return Returns the UUID
     */
    @JsonGetter("DeviceID")
    public UUID getDeviceID() {
        return deviceID;
    }

    /**
     * Setter for DeviceID.
     * The generated ID (UUID v4) for the device. It can be used as: - the MQTT Client ID when
     * connecting to the Message Exchange system - a parameter when asking for the connection
     * endpoint - a parameter when finishing the device registration - a parameter when
     * unregistering the device
     * @param deviceID Value for UUID
     */
    @JsonSetter("DeviceID")
    public void setDeviceID(UUID deviceID) {
        this.deviceID = deviceID;
    }

    /**
     * Getter for ClientType.
     * The type of the client that is to be registered. This is one of the major traffic participant
     * groups considered in V2X communication. The system uses this value to define which topics the
     * client will be able to publish and subscribe to. Values: - **Vehicle** - Vehicle with an
     * enclosure around the passengers. (Subtypes: Motorcycle, PassengerCar, Truck, Bus,
     * EmergencyVehicle, SchoolBus, MaintenanceVehicle) - **VulnerableRoadUser** - Traffic
     * participants without a protecting enclosure. (Subtypes: Bicycle, Pedestrian, Scooter) -
     * **TrafficLightController** - A Traffic light controller system. (Subtypes: NA) -
     * **InfrastructureSensor** - Sensors that are deployed in the infrastructure. (Subtypes:
     * RoadSideUnit, Camera, Lidar, Radar, InductiveLoop, MagneticSensor) - **OnboardSensor** -
     * Sensors that are onboard on a vehicle(Subtypes: Camera, Lidar, Radar) - **Software** - A
     * software system or application. (Subtypes: Platform, Application, NA)
     * @return Returns the EtxClientTypeEnum
     */
    @JsonGetter("ClientType")
    public EtxClientTypeEnum getClientType() {
        return clientType;
    }

    /**
     * Setter for ClientType.
     * The type of the client that is to be registered. This is one of the major traffic participant
     * groups considered in V2X communication. The system uses this value to define which topics the
     * client will be able to publish and subscribe to. Values: - **Vehicle** - Vehicle with an
     * enclosure around the passengers. (Subtypes: Motorcycle, PassengerCar, Truck, Bus,
     * EmergencyVehicle, SchoolBus, MaintenanceVehicle) - **VulnerableRoadUser** - Traffic
     * participants without a protecting enclosure. (Subtypes: Bicycle, Pedestrian, Scooter) -
     * **TrafficLightController** - A Traffic light controller system. (Subtypes: NA) -
     * **InfrastructureSensor** - Sensors that are deployed in the infrastructure. (Subtypes:
     * RoadSideUnit, Camera, Lidar, Radar, InductiveLoop, MagneticSensor) - **OnboardSensor** -
     * Sensors that are onboard on a vehicle(Subtypes: Camera, Lidar, Radar) - **Software** - A
     * software system or application. (Subtypes: Platform, Application, NA)
     * @param clientType Value for EtxClientTypeEnum
     */
    @JsonSetter("ClientType")
    public void setClientType(EtxClientTypeEnum clientType) {
        this.clientType = clientType;
    }

    /**
     * Getter for ClientSubtype.
     * The subtype or subgroup of the client type. This further specifies the client type. For
     * example it will specify if the client is a passenger car or a truck. See the ClientType
     * description for the supported Subtypes for each client type.
     * @return Returns the ClientSubtypeEnum
     */
    @JsonGetter("ClientSubtype")
    public ClientSubtypeEnum getClientSubtype() {
        return clientSubtype;
    }

    /**
     * Setter for ClientSubtype.
     * The subtype or subgroup of the client type. This further specifies the client type. For
     * example it will specify if the client is a passenger car or a truck. See the ClientType
     * description for the supported Subtypes for each client type.
     * @param clientSubtype Value for ClientSubtypeEnum
     */
    @JsonSetter("ClientSubtype")
    public void setClientSubtype(ClientSubtypeEnum clientSubtype) {
        this.clientSubtype = clientSubtype;
    }

    /**
     * Getter for MecIds.
     * @return Returns the List of String
     */
    @JsonGetter("MecIds")
    public List<String> getMecIds() {
        return mecIds;
    }

    /**
     * Setter for MecIds.
     * @param mecIds Value for List of String
     */
    @JsonSetter("MecIds")
    public void setMecIds(List<String> mecIds) {
        this.mecIds = mecIds;
    }

    /**
     * Converts this DevicesResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DevicesResponse [" + "deviceID=" + deviceID + ", clientType=" + clientType
                + ", clientSubtype=" + clientSubtype + ", mecIds=" + mecIds + "]";
    }

    /**
     * Builds a new {@link DevicesResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DevicesResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deviceID, clientType, clientSubtype, mecIds);
        return builder;
    }

    /**
     * Class to build instances of {@link DevicesResponse}.
     */
    public static class Builder {
        private UUID deviceID;
        private EtxClientTypeEnum clientType;
        private ClientSubtypeEnum clientSubtype;
        private List<String> mecIds;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deviceID  UUID value for deviceID.
         * @param  clientType  EtxClientTypeEnum value for clientType.
         * @param  clientSubtype  ClientSubtypeEnum value for clientSubtype.
         * @param  mecIds  List of String value for mecIds.
         */
        public Builder(UUID deviceID, EtxClientTypeEnum clientType, ClientSubtypeEnum clientSubtype,
                List<String> mecIds) {
            this.deviceID = deviceID;
            this.clientType = clientType;
            this.clientSubtype = clientSubtype;
            this.mecIds = mecIds;
        }

        /**
         * Setter for deviceID.
         * @param  deviceID  UUID value for deviceID.
         * @return Builder
         */
        public Builder deviceID(UUID deviceID) {
            this.deviceID = deviceID;
            return this;
        }

        /**
         * Setter for clientType.
         * @param  clientType  EtxClientTypeEnum value for clientType.
         * @return Builder
         */
        public Builder clientType(EtxClientTypeEnum clientType) {
            this.clientType = clientType;
            return this;
        }

        /**
         * Setter for clientSubtype.
         * @param  clientSubtype  ClientSubtypeEnum value for clientSubtype.
         * @return Builder
         */
        public Builder clientSubtype(ClientSubtypeEnum clientSubtype) {
            this.clientSubtype = clientSubtype;
            return this;
        }

        /**
         * Setter for mecIds.
         * @param  mecIds  List of String value for mecIds.
         * @return Builder
         */
        public Builder mecIds(List<String> mecIds) {
            this.mecIds = mecIds;
            return this;
        }

        /**
         * Builds a new {@link DevicesResponse} object using the set fields.
         * @return {@link DevicesResponse}
         */
        public DevicesResponse build() {
            return new DevicesResponse(deviceID, clientType, clientSubtype, mecIds);
        }
    }
}
