/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for EmergencyVehicleApproachingCauseCode type.
 */
public class EmergencyVehicleApproachingCauseCode {
    private int emergencyVehicleApproaching95;

    /**
     * Default constructor.
     */
    public EmergencyVehicleApproachingCauseCode() {
    }

    /**
     * Initialization constructor.
     * @param  emergencyVehicleApproaching95  int value for emergencyVehicleApproaching95.
     */
    @JsonCreator
    public EmergencyVehicleApproachingCauseCode(
            @JsonProperty("emergencyVehicleApproaching95") int emergencyVehicleApproaching95) {
        this.emergencyVehicleApproaching95 = emergencyVehicleApproaching95;
    }

    /**
     * Getter for EmergencyVehicleApproaching95.
     * The value shall be set to: - 0 `unavailable` - in case further detailed information on the
     * emergency vehicle approaching event is unavailable, - 1 `emergencyVehicleApproaching` - in
     * case an operating emergency vehicle is approaching, - 2 `prioritizedVehicleApproaching` - in
     * case a prioritized vehicle is approaching, - 3-255 - reserved for future usage.
     * @return Returns the int
     */
    @JsonGetter("emergencyVehicleApproaching95")
    public int getEmergencyVehicleApproaching95() {
        return emergencyVehicleApproaching95;
    }

    /**
     * Setter for EmergencyVehicleApproaching95.
     * The value shall be set to: - 0 `unavailable` - in case further detailed information on the
     * emergency vehicle approaching event is unavailable, - 1 `emergencyVehicleApproaching` - in
     * case an operating emergency vehicle is approaching, - 2 `prioritizedVehicleApproaching` - in
     * case a prioritized vehicle is approaching, - 3-255 - reserved for future usage.
     * @param emergencyVehicleApproaching95 Value for int
     */
    @JsonSetter("emergencyVehicleApproaching95")
    public void setEmergencyVehicleApproaching95(int emergencyVehicleApproaching95) {
        this.emergencyVehicleApproaching95 = emergencyVehicleApproaching95;
    }

    /**
     * Converts this EmergencyVehicleApproachingCauseCode into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EmergencyVehicleApproachingCauseCode [" + "emergencyVehicleApproaching95="
                + emergencyVehicleApproaching95 + "]";
    }

    /**
     * Builds a new {@link EmergencyVehicleApproachingCauseCode.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EmergencyVehicleApproachingCauseCode.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(emergencyVehicleApproaching95);
        return builder;
    }

    /**
     * Class to build instances of {@link EmergencyVehicleApproachingCauseCode}.
     */
    public static class Builder {
        private int emergencyVehicleApproaching95;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  emergencyVehicleApproaching95  int value for emergencyVehicleApproaching95.
         */
        public Builder(int emergencyVehicleApproaching95) {
            this.emergencyVehicleApproaching95 = emergencyVehicleApproaching95;
        }

        /**
         * Setter for emergencyVehicleApproaching95.
         * @param  emergencyVehicleApproaching95  int value for emergencyVehicleApproaching95.
         * @return Builder
         */
        public Builder emergencyVehicleApproaching95(int emergencyVehicleApproaching95) {
            this.emergencyVehicleApproaching95 = emergencyVehicleApproaching95;
            return this;
        }

        /**
         * Builds a new {@link EmergencyVehicleApproachingCauseCode} object using the set fields.
         * @return {@link EmergencyVehicleApproachingCauseCode}
         */
        public EmergencyVehicleApproachingCauseCode build() {
            return new EmergencyVehicleApproachingCauseCode(emergencyVehicleApproaching95);
        }
    }
}
