/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for EtsiAlertMessage type.
 */
public class EtsiAlertMessage {
    private EtsiAlertPayload etsiAlert;

    /**
     * Default constructor.
     */
    public EtsiAlertMessage() {
    }

    /**
     * Initialization constructor.
     * @param  etsiAlert  EtsiAlertPayload value for etsiAlert.
     */
    public EtsiAlertMessage(
            EtsiAlertPayload etsiAlert) {
        this.etsiAlert = etsiAlert;
    }

    /**
     * Getter for EtsiAlert.
     * DENM (Decentralized Environmental Notification Message) payload as defined in ETSI.
     * @return Returns the EtsiAlertPayload
     */
    @JsonGetter("etsiAlert")
    public EtsiAlertPayload getEtsiAlert() {
        return etsiAlert;
    }

    /**
     * Setter for EtsiAlert.
     * DENM (Decentralized Environmental Notification Message) payload as defined in ETSI.
     * @param etsiAlert Value for EtsiAlertPayload
     */
    @JsonSetter("etsiAlert")
    public void setEtsiAlert(EtsiAlertPayload etsiAlert) {
        this.etsiAlert = etsiAlert;
    }

    /**
     * Converts this EtsiAlertMessage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EtsiAlertMessage [" + "etsiAlert=" + etsiAlert + "]";
    }

    /**
     * Builds a new {@link EtsiAlertMessage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EtsiAlertMessage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(etsiAlert);
        return builder;
    }

    /**
     * Class to build instances of {@link EtsiAlertMessage}.
     */
    public static class Builder {
        private EtsiAlertPayload etsiAlert;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  etsiAlert  EtsiAlertPayload value for etsiAlert.
         */
        public Builder(EtsiAlertPayload etsiAlert) {
            this.etsiAlert = etsiAlert;
        }

        /**
         * Setter for etsiAlert.
         * @param  etsiAlert  EtsiAlertPayload value for etsiAlert.
         * @return Builder
         */
        public Builder etsiAlert(EtsiAlertPayload etsiAlert) {
            this.etsiAlert = etsiAlert;
            return this;
        }

        /**
         * Builds a new {@link EtsiAlertMessage} object using the set fields.
         * @return {@link EtsiAlertMessage}
         */
        public EtsiAlertMessage build() {
            return new EtsiAlertMessage(etsiAlert);
        }
    }
}
