/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * ETXExpectedTypeEnum to be used.
 */
public enum ETXExpectedTypeEnum {
    BASE64,

    JSON;

    private static TreeMap<String, ETXExpectedTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        BASE64.value = "BASE64";
        JSON.value = "JSON";

        valueMap.put("BASE64", BASE64);
        valueMap.put("JSON", JSON);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ETXExpectedTypeEnum constructFromString(String toConvert) throws IOException {
        ETXExpectedTypeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ETXExpectedTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ETXExpectedTypeEnum values to list of string values.
     * @param toConvert The list of ETXExpectedTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ETXExpectedTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ETXExpectedTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 