/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ETXMAPMessageGeoJSONPolygon type.
 */
public class ETXMAPMessageGeoJSONPolygon {
    private ETXMessageStandardEnum messageStandard;
    private Object geoJson;
    private ETXExpectedTypeEnum expectedType;
    private String pageToken;
    private Integer pageSize;

    /**
     * Default constructor.
     */
    public ETXMAPMessageGeoJSONPolygon() {
        messageStandard = ETXMessageStandardEnum.SAE;
        expectedType = ETXExpectedTypeEnum.BASE64;
        pageSize = 200;
    }

    /**
     * Initialization constructor.
     * @param  geoJson  Object value for geoJson.
     * @param  messageStandard  ETXMessageStandardEnum value for messageStandard.
     * @param  expectedType  ETXExpectedTypeEnum value for expectedType.
     * @param  pageToken  String value for pageToken.
     * @param  pageSize  Integer value for pageSize.
     */
    public ETXMAPMessageGeoJSONPolygon(
            Object geoJson,
            ETXMessageStandardEnum messageStandard,
            ETXExpectedTypeEnum expectedType,
            String pageToken,
            Integer pageSize) {
        this.messageStandard = messageStandard;
        this.geoJson = geoJson;
        this.expectedType = expectedType;
        this.pageToken = pageToken;
        this.pageSize = pageSize;
    }

    /**
     * Initialization constructor.
     * @param  geoJson  Object value for geoJson.
     */
    @JsonCreator
    protected ETXMAPMessageGeoJSONPolygon(
            @JsonProperty("geoJson") Object geoJson) {
        this(geoJson, null, null, null, null);
    }

    /**
     * Getter for MessageStandard.
     * V2X messaging standard selection. Accepted values are 'sae' (SAE J2735) and 'etsi' (ETSI TS
     * 103 301).
     * @return Returns the ETXMessageStandardEnum
     */
    @JsonGetter("messageStandard")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ETXMessageStandardEnum getMessageStandard() {
        return messageStandard;
    }

    /**
     * Setter for MessageStandard.
     * V2X messaging standard selection. Accepted values are 'sae' (SAE J2735) and 'etsi' (ETSI TS
     * 103 301).
     * @param messageStandard Value for ETXMessageStandardEnum
     */
    @JsonSetter("messageStandard")
    public void setMessageStandard(ETXMessageStandardEnum messageStandard) {
        this.messageStandard = messageStandard;
    }

    /**
     * Getter for GeoJson.
     * GeoJSON Polygon defining the area to retrieve MAP messages for.
     * @return Returns the Object
     */
    @JsonGetter("geoJson")
    public Object getGeoJson() {
        return geoJson;
    }

    /**
     * Setter for GeoJson.
     * GeoJSON Polygon defining the area to retrieve MAP messages for.
     * @param geoJson Value for Object
     */
    @JsonSetter("geoJson")
    public void setGeoJson(Object geoJson) {
        this.geoJson = geoJson;
    }

    /**
     * Getter for ExpectedType.
     * The format of the payload in the response body.
     * @return Returns the ETXExpectedTypeEnum
     */
    @JsonGetter("expectedType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ETXExpectedTypeEnum getExpectedType() {
        return expectedType;
    }

    /**
     * Setter for ExpectedType.
     * The format of the payload in the response body.
     * @param expectedType Value for ETXExpectedTypeEnum
     */
    @JsonSetter("expectedType")
    public void setExpectedType(ETXExpectedTypeEnum expectedType) {
        this.expectedType = expectedType;
    }

    /**
     * Getter for PageToken.
     * Base64 encoded token used to retrieve the next page of results
     * @return Returns the String
     */
    @JsonGetter("pageToken")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPageToken() {
        return pageToken;
    }

    /**
     * Setter for PageToken.
     * Base64 encoded token used to retrieve the next page of results
     * @param pageToken Value for String
     */
    @JsonSetter("pageToken")
    public void setPageToken(String pageToken) {
        this.pageToken = pageToken;
    }

    /**
     * Getter for PageSize.
     * Maximum number of records to return in a single page
     * @return Returns the Integer
     */
    @JsonGetter("pageSize")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPageSize() {
        return pageSize;
    }

    /**
     * Setter for PageSize.
     * Maximum number of records to return in a single page
     * @param pageSize Value for Integer
     */
    @JsonSetter("pageSize")
    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * Converts this ETXMAPMessageGeoJSONPolygon into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ETXMAPMessageGeoJSONPolygon [" + "geoJson=" + geoJson + ", messageStandard="
                + messageStandard + ", expectedType=" + expectedType + ", pageToken=" + pageToken
                + ", pageSize=" + pageSize + "]";
    }

    /**
     * Builds a new {@link ETXMAPMessageGeoJSONPolygon.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ETXMAPMessageGeoJSONPolygon.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(geoJson)
                .messageStandard(getMessageStandard())
                .expectedType(getExpectedType())
                .pageToken(getPageToken())
                .pageSize(getPageSize());
        return builder;
    }

    /**
     * Class to build instances of {@link ETXMAPMessageGeoJSONPolygon}.
     */
    public static class Builder {
        private Object geoJson;
        private ETXMessageStandardEnum messageStandard = ETXMessageStandardEnum.SAE;
        private ETXExpectedTypeEnum expectedType = ETXExpectedTypeEnum.BASE64;
        private String pageToken;
        private Integer pageSize = 200;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  geoJson  Object value for geoJson.
         */
        public Builder(Object geoJson) {
            this.geoJson = geoJson;
        }

        /**
         * Setter for geoJson.
         * @param  geoJson  Object value for geoJson.
         * @return Builder
         */
        public Builder geoJson(Object geoJson) {
            this.geoJson = geoJson;
            return this;
        }

        /**
         * Setter for messageStandard.
         * @param  messageStandard  ETXMessageStandardEnum value for messageStandard.
         * @return Builder
         */
        public Builder messageStandard(ETXMessageStandardEnum messageStandard) {
            this.messageStandard = messageStandard;
            return this;
        }

        /**
         * Setter for expectedType.
         * @param  expectedType  ETXExpectedTypeEnum value for expectedType.
         * @return Builder
         */
        public Builder expectedType(ETXExpectedTypeEnum expectedType) {
            this.expectedType = expectedType;
            return this;
        }

        /**
         * Setter for pageToken.
         * @param  pageToken  String value for pageToken.
         * @return Builder
         */
        public Builder pageToken(String pageToken) {
            this.pageToken = pageToken;
            return this;
        }

        /**
         * Setter for pageSize.
         * @param  pageSize  Integer value for pageSize.
         * @return Builder
         */
        public Builder pageSize(Integer pageSize) {
            this.pageSize = pageSize;
            return this;
        }

        /**
         * Builds a new {@link ETXMAPMessageGeoJSONPolygon} object using the set fields.
         * @return {@link ETXMAPMessageGeoJSONPolygon}
         */
        public ETXMAPMessageGeoJSONPolygon build() {
            return new ETXMAPMessageGeoJSONPolygon(geoJson, messageStandard, expectedType,
                    pageToken, pageSize);
        }
    }
}
