/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ETXMAPDataIngestRequest type.
 */
public class ETXMAPDataIngestRequest {
    private int messageId;
    private Object value;
    private Integer msgIssueRevision;

    /**
     * Default constructor.
     */
    public ETXMAPDataIngestRequest() {
    }

    /**
     * Initialization constructor.
     * @param  messageId  int value for messageId.
     * @param  value  Object value for value.
     * @param  msgIssueRevision  Integer value for msgIssueRevision.
     */
    public ETXMAPDataIngestRequest(
            int messageId,
            Object value,
            Integer msgIssueRevision) {
        this.messageId = messageId;
        this.value = value;
        this.msgIssueRevision = msgIssueRevision;
    }

    /**
     * Getter for MessageId.
     * SAE J2735 DSRCmsgID for the MAP message type.
     * @return Returns the int
     */
    @JsonGetter("messageId")
    public int getMessageId() {
        return messageId;
    }

    /**
     * Setter for MessageId.
     * SAE J2735 DSRCmsgID for the MAP message type.
     * @param messageId Value for int
     */
    @JsonSetter("messageId")
    public void setMessageId(int messageId) {
        this.messageId = messageId;
    }

    /**
     * Getter for Value.
     * The decoded MAP message body containing intersection and lane data.
     * @return Returns the Object
     */
    @JsonGetter("value")
    public Object getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * The decoded MAP message body containing intersection and lane data.
     * @param value Value for Object
     */
    @JsonSetter("value")
    public void setValue(Object value) {
        this.value = value;
    }

    /**
     * Getter for MsgIssueRevision.
     * Issue revision number of the MAP message.
     * @return Returns the Integer
     */
    @JsonGetter("msgIssueRevision")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getMsgIssueRevision() {
        return msgIssueRevision;
    }

    /**
     * Setter for MsgIssueRevision.
     * Issue revision number of the MAP message.
     * @param msgIssueRevision Value for Integer
     */
    @JsonSetter("msgIssueRevision")
    public void setMsgIssueRevision(Integer msgIssueRevision) {
        this.msgIssueRevision = msgIssueRevision;
    }

    /**
     * Converts this ETXMAPDataIngestRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ETXMAPDataIngestRequest [" + "messageId=" + messageId + ", value=" + value
                + ", msgIssueRevision=" + msgIssueRevision + "]";
    }

    /**
     * Builds a new {@link ETXMAPDataIngestRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ETXMAPDataIngestRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(messageId, value)
                .msgIssueRevision(getMsgIssueRevision());
        return builder;
    }

    /**
     * Class to build instances of {@link ETXMAPDataIngestRequest}.
     */
    public static class Builder {
        private int messageId;
        private Object value;
        private Integer msgIssueRevision;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  messageId  int value for messageId.
         * @param  value  Object value for value.
         */
        public Builder(int messageId, Object value) {
            this.messageId = messageId;
            this.value = value;
        }

        /**
         * Setter for messageId.
         * @param  messageId  int value for messageId.
         * @return Builder
         */
        public Builder messageId(int messageId) {
            this.messageId = messageId;
            return this;
        }

        /**
         * Setter for value.
         * @param  value  Object value for value.
         * @return Builder
         */
        public Builder value(Object value) {
            this.value = value;
            return this;
        }

        /**
         * Setter for msgIssueRevision.
         * @param  msgIssueRevision  Integer value for msgIssueRevision.
         * @return Builder
         */
        public Builder msgIssueRevision(Integer msgIssueRevision) {
            this.msgIssueRevision = msgIssueRevision;
            return this;
        }

        /**
         * Builds a new {@link ETXMAPDataIngestRequest} object using the set fields.
         * @return {@link ETXMAPDataIngestRequest}
         */
        public ETXMAPDataIngestRequest build() {
            return new ETXMAPDataIngestRequest(messageId, value, msgIssueRevision);
        }
    }
}
