/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.thingspace.models.containers.CauseCodeChoice;

/**
 * This is a model class for EventType type.
 */
public class EventType {
    private CauseCodeChoice ccAndScc;

    /**
     * Default constructor.
     */
    public EventType() {
    }

    /**
     * Initialization constructor.
     * @param  ccAndScc  CauseCodeChoice value for ccAndScc.
     */
    public EventType(
            CauseCodeChoice ccAndScc) {
        this.ccAndScc = ccAndScc;
    }

    /**
     * Getter for CcAndScc.
     * The main cause of a detected event. Each entry is of a different type and represents the sub
     * cause code.
     * @return Returns the CauseCodeChoice
     */
    @JsonGetter("ccAndScc")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CauseCodeChoice getCcAndScc() {
        return ccAndScc;
    }

    /**
     * Setter for CcAndScc.
     * The main cause of a detected event. Each entry is of a different type and represents the sub
     * cause code.
     * @param ccAndScc Value for CauseCodeChoice
     */
    @JsonSetter("ccAndScc")
    public void setCcAndScc(CauseCodeChoice ccAndScc) {
        this.ccAndScc = ccAndScc;
    }

    /**
     * Converts this EventType into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EventType [" + "ccAndScc=" + ccAndScc + "]";
    }

    /**
     * Builds a new {@link EventType.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EventType.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .ccAndScc(getCcAndScc());
        return builder;
    }

    /**
     * Class to build instances of {@link EventType}.
     */
    public static class Builder {
        private CauseCodeChoice ccAndScc;



        /**
         * Setter for ccAndScc.
         * @param  ccAndScc  CauseCodeChoice value for ccAndScc.
         * @return Builder
         */
        public Builder ccAndScc(CauseCodeChoice ccAndScc) {
            this.ccAndScc = ccAndScc;
            return this;
        }

        /**
         * Builds a new {@link EventType} object using the set fields.
         * @return {@link EventType}
         */
        public EventType build() {
            return new EventType(ccAndScc);
        }
    }
}
