/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.thingspace.models.containers.TextPhraseOrITIS;
import java.util.List;

/**
 * This is a model class for ExitServiceContent type.
 */
public class ExitServiceContent {
    private List<TextPhraseOrITIS> exitService;

    /**
     * Default constructor.
     */
    public ExitServiceContent() {
    }

    /**
     * Initialization constructor.
     * @param  exitService  List of TextPhraseOrITIS value for exitService.
     */
    @JsonCreator
    public ExitServiceContent(
            @JsonProperty("exitService") List<TextPhraseOrITIS> exitService) {
        this.exitService = exitService;
    }

    /**
     * Getter for ExitService.
     * List of roadside available services.
     * @return Returns the List of TextPhraseOrITIS
     */
    @JsonGetter("exitService")
    public List<TextPhraseOrITIS> getExitService() {
        return exitService;
    }

    /**
     * Setter for ExitService.
     * List of roadside available services.
     * @param exitService Value for List of TextPhraseOrITIS
     */
    @JsonSetter("exitService")
    public void setExitService(List<TextPhraseOrITIS> exitService) {
        this.exitService = exitService;
    }

    /**
     * Converts this ExitServiceContent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ExitServiceContent [" + "exitService=" + exitService + "]";
    }

    /**
     * Builds a new {@link ExitServiceContent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ExitServiceContent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(exitService);
        return builder;
    }

    /**
     * Class to build instances of {@link ExitServiceContent}.
     */
    public static class Builder {
        private List<TextPhraseOrITIS> exitService;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  exitService  List of TextPhraseOrITIS value for exitService.
         */
        public Builder(List<TextPhraseOrITIS> exitService) {
            this.exitService = exitService;
        }

        /**
         * Setter for exitService.
         * @param  exitService  List of TextPhraseOrITIS value for exitService.
         * @return Builder
         */
        public Builder exitService(List<TextPhraseOrITIS> exitService) {
            this.exitService = exitService;
            return this;
        }

        /**
         * Builds a new {@link ExitServiceContent} object using the set fields.
         * @return {@link ExitServiceContent}
         */
        public ExitServiceContent build() {
            return new ExitServiceContent(exitService);
        }
    }
}
