/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for FurtherInfoMsgId type.
 */
public class FurtherInfoMsgId {
    private String furtherInfoID;

    /**
     * Default constructor.
     */
    public FurtherInfoMsgId() {
    }

    /**
     * Initialization constructor.
     * @param  furtherInfoID  String value for furtherInfoID.
     */
    @JsonCreator
    public FurtherInfoMsgId(
            @JsonProperty("furtherInfoID") String furtherInfoID) {
        this.furtherInfoID = furtherInfoID;
    }

    /**
     * Getter for FurtherInfoID.
     * Links to ATIS message. A link to any other incident information data that may be available in
     * the normal ATIS incident description or other messages. The value is described as a
     * 4-character hexadecimal string.
     * @return Returns the String
     */
    @JsonGetter("furtherInfoID")
    public String getFurtherInfoID() {
        return furtherInfoID;
    }

    /**
     * Setter for FurtherInfoID.
     * Links to ATIS message. A link to any other incident information data that may be available in
     * the normal ATIS incident description or other messages. The value is described as a
     * 4-character hexadecimal string.
     * @param furtherInfoID Value for String
     */
    @JsonSetter("furtherInfoID")
    public void setFurtherInfoID(String furtherInfoID) {
        this.furtherInfoID = furtherInfoID;
    }

    /**
     * Converts this FurtherInfoMsgId into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FurtherInfoMsgId [" + "furtherInfoID=" + furtherInfoID + "]";
    }

    /**
     * Builds a new {@link FurtherInfoMsgId.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FurtherInfoMsgId.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(furtherInfoID);
        return builder;
    }

    /**
     * Class to build instances of {@link FurtherInfoMsgId}.
     */
    public static class Builder {
        private String furtherInfoID;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  furtherInfoID  String value for furtherInfoID.
         */
        public Builder(String furtherInfoID) {
            this.furtherInfoID = furtherInfoID;
        }

        /**
         * Setter for furtherInfoID.
         * @param  furtherInfoID  String value for furtherInfoID.
         * @return Builder
         */
        public Builder furtherInfoID(String furtherInfoID) {
            this.furtherInfoID = furtherInfoID;
            return this;
        }

        /**
         * Builds a new {@link FurtherInfoMsgId} object using the set fields.
         * @return {@link FurtherInfoMsgId}
         */
        public FurtherInfoMsgId build() {
            return new FurtherInfoMsgId(furtherInfoID);
        }
    }
}
