/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GenericMessage type.
 */
public class GenericMessage {
    private GenericPayload generic;

    /**
     * Default constructor.
     */
    public GenericMessage() {
    }

    /**
     * Initialization constructor.
     * @param  generic  GenericPayload value for generic.
     */
    public GenericMessage(
            GenericPayload generic) {
        this.generic = generic;
    }

    /**
     * Getter for Generic.
     * Custom message which is defined by the user and can support "any" message type or format.
     * **Note:** ETX prefers the j2735 or the j2735_gr encoding and only vendor specific message
     * types are allowed to be published in different message formats.
     * @return Returns the GenericPayload
     */
    @JsonGetter("generic")
    public GenericPayload getGeneric() {
        return generic;
    }

    /**
     * Setter for Generic.
     * Custom message which is defined by the user and can support "any" message type or format.
     * **Note:** ETX prefers the j2735 or the j2735_gr encoding and only vendor specific message
     * types are allowed to be published in different message formats.
     * @param generic Value for GenericPayload
     */
    @JsonSetter("generic")
    public void setGeneric(GenericPayload generic) {
        this.generic = generic;
    }

    /**
     * Converts this GenericMessage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GenericMessage [" + "generic=" + generic + "]";
    }

    /**
     * Builds a new {@link GenericMessage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GenericMessage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(generic);
        return builder;
    }

    /**
     * Class to build instances of {@link GenericMessage}.
     */
    public static class Builder {
        private GenericPayload generic;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  generic  GenericPayload value for generic.
         */
        public Builder(GenericPayload generic) {
            this.generic = generic;
        }

        /**
         * Setter for generic.
         * @param  generic  GenericPayload value for generic.
         * @return Builder
         */
        public Builder generic(GenericPayload generic) {
            this.generic = generic;
            return this;
        }

        /**
         * Builds a new {@link GenericMessage} object using the set fields.
         * @return {@link GenericMessage}
         */
        public GenericMessage build() {
            return new GenericMessage(generic);
        }
    }
}
