/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.thingspace.models.containers.TextPhraseOrITIS;
import java.util.List;

/**
 * This is a model class for GenericSignContent type.
 */
public class GenericSignContent {
    private List<TextPhraseOrITIS> genericSign;

    /**
     * Default constructor.
     */
    public GenericSignContent() {
    }

    /**
     * Initialization constructor.
     * @param  genericSign  List of TextPhraseOrITIS value for genericSign.
     */
    @JsonCreator
    public GenericSignContent(
            @JsonProperty("genericSign") List<TextPhraseOrITIS> genericSign) {
        this.genericSign = genericSign;
    }

    /**
     * Getter for GenericSign.
     * List of MUTCD signs and directions.
     * @return Returns the List of TextPhraseOrITIS
     */
    @JsonGetter("genericSign")
    public List<TextPhraseOrITIS> getGenericSign() {
        return genericSign;
    }

    /**
     * Setter for GenericSign.
     * List of MUTCD signs and directions.
     * @param genericSign Value for List of TextPhraseOrITIS
     */
    @JsonSetter("genericSign")
    public void setGenericSign(List<TextPhraseOrITIS> genericSign) {
        this.genericSign = genericSign;
    }

    /**
     * Converts this GenericSignContent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GenericSignContent [" + "genericSign=" + genericSign + "]";
    }

    /**
     * Builds a new {@link GenericSignContent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GenericSignContent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(genericSign);
        return builder;
    }

    /**
     * Class to build instances of {@link GenericSignContent}.
     */
    public static class Builder {
        private List<TextPhraseOrITIS> genericSign;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  genericSign  List of TextPhraseOrITIS value for genericSign.
         */
        public Builder(List<TextPhraseOrITIS> genericSign) {
            this.genericSign = genericSign;
        }

        /**
         * Setter for genericSign.
         * @param  genericSign  List of TextPhraseOrITIS value for genericSign.
         * @return Builder
         */
        public Builder genericSign(List<TextPhraseOrITIS> genericSign) {
            this.genericSign = genericSign;
            return this;
        }

        /**
         * Builds a new {@link GenericSignContent} object using the set fields.
         * @return {@link GenericSignContent}
         */
        public GenericSignContent build() {
            return new GenericSignContent(genericSign);
        }
    }
}
