/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for GeofencePolygon type.
 */
public class GeofencePolygon {
    private ETXMAPMessageGeofenceGeometryEnum type;
    private List<List<Double>> coordinates;

    /**
     * Default constructor.
     */
    public GeofencePolygon() {
    }

    /**
     * Initialization constructor.
     * @param  type  ETXMAPMessageGeofenceGeometryEnum value for type.
     * @param  coordinates  List of Double value for coordinates.
     */
    public GeofencePolygon(
            ETXMAPMessageGeofenceGeometryEnum type,
            List<List<Double>> coordinates) {
        this.type = type;
        this.coordinates = coordinates;
    }

    /**
     * Getter for Type.
     * Type of the GeoJSON geometry, must be 'Polygon'.
     * @return Returns the ETXMAPMessageGeofenceGeometryEnum
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ETXMAPMessageGeofenceGeometryEnum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Type of the GeoJSON geometry, must be 'Polygon'.
     * @param type Value for ETXMAPMessageGeofenceGeometryEnum
     */
    @JsonSetter("type")
    public void setType(ETXMAPMessageGeofenceGeometryEnum type) {
        this.type = type;
    }

    /**
     * Getter for Coordinates.
     * Coordinates of the GeoJSON polygon. Rules for a valid GeoJSON Polygon: - Must contain between
     * 4 and 50 points. - Must be an array of linear rings (arrays of positions). - The first linear
     * ring represents the outer boundary; subsequent rings would represent holes. Holes are not
     * supported, so only one linear ring should be defined in a polygon. - Each linear ring must
     * have at least 4 positions, and the first and last positions must be identical to close the
     * polygon ring. - A linear ring must follow the right-hand rule with respect to the area it
     * bounds: exterior rings (outer boundery) are counterclockwise. - Each position is an array of
     * two numbers: [longitude, latitude]. - Longitude and latitude values must be in decimal
     * degrees. - Longitude must be ranging from -180 to 180. - Latitude must be ranging from -90 to
     * 90. - The polygon must not self-intersect.
     * @return Returns the List of Double
     */
    @JsonGetter("coordinates")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<List<Double>> getCoordinates() {
        return coordinates;
    }

    /**
     * Setter for Coordinates.
     * Coordinates of the GeoJSON polygon. Rules for a valid GeoJSON Polygon: - Must contain between
     * 4 and 50 points. - Must be an array of linear rings (arrays of positions). - The first linear
     * ring represents the outer boundary; subsequent rings would represent holes. Holes are not
     * supported, so only one linear ring should be defined in a polygon. - Each linear ring must
     * have at least 4 positions, and the first and last positions must be identical to close the
     * polygon ring. - A linear ring must follow the right-hand rule with respect to the area it
     * bounds: exterior rings (outer boundery) are counterclockwise. - Each position is an array of
     * two numbers: [longitude, latitude]. - Longitude and latitude values must be in decimal
     * degrees. - Longitude must be ranging from -180 to 180. - Latitude must be ranging from -90 to
     * 90. - The polygon must not self-intersect.
     * @param coordinates Value for List of Double
     */
    @JsonSetter("coordinates")
    public void setCoordinates(List<List<Double>> coordinates) {
        this.coordinates = coordinates;
    }

    /**
     * Converts this GeofencePolygon into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeofencePolygon [" + "type=" + type + ", coordinates=" + coordinates + "]";
    }

    /**
     * Builds a new {@link GeofencePolygon.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeofencePolygon.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType())
                .coordinates(getCoordinates());
        return builder;
    }

    /**
     * Class to build instances of {@link GeofencePolygon}.
     */
    public static class Builder {
        private ETXMAPMessageGeofenceGeometryEnum type;
        private List<List<Double>> coordinates;



        /**
         * Setter for type.
         * @param  type  ETXMAPMessageGeofenceGeometryEnum value for type.
         * @return Builder
         */
        public Builder type(ETXMAPMessageGeofenceGeometryEnum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for coordinates.
         * @param  coordinates  List of Double value for coordinates.
         * @return Builder
         */
        public Builder coordinates(List<List<Double>> coordinates) {
            this.coordinates = coordinates;
            return this;
        }

        /**
         * Builds a new {@link GeofencePolygon} object using the set fields.
         * @return {@link GeofencePolygon}
         */
        public GeofencePolygon build() {
            return new GeofencePolygon(type, coordinates);
        }
    }
}
