/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for GeoFence type.
 */
public class GeoFence {
    private TypeEnum type;
    private List<FeatureItem> features;

    /**
     * Default constructor.
     */
    public GeoFence() {
    }

    /**
     * Initialization constructor.
     * @param  type  TypeEnum value for type.
     * @param  features  List of FeatureItem value for features.
     */
    public GeoFence(
            TypeEnum type,
            List<FeatureItem> features) {
        this.type = type;
        this.features = features;
    }

    /**
     * Getter for Type.
     * @return Returns the TypeEnum
     */
    @JsonGetter("type")
    public TypeEnum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for TypeEnum
     */
    @JsonSetter("type")
    public void setType(TypeEnum type) {
        this.type = type;
    }

    /**
     * Getter for Features.
     * @return Returns the List of FeatureItem
     */
    @JsonGetter("features")
    public List<FeatureItem> getFeatures() {
        return features;
    }

    /**
     * Setter for Features.
     * @param features Value for List of FeatureItem
     */
    @JsonSetter("features")
    public void setFeatures(List<FeatureItem> features) {
        this.features = features;
    }

    /**
     * Converts this GeoFence into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeoFence [" + "type=" + type + ", features=" + features + "]";
    }

    /**
     * Builds a new {@link GeoFence.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeoFence.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, features);
        return builder;
    }

    /**
     * Class to build instances of {@link GeoFence}.
     */
    public static class Builder {
        private TypeEnum type;
        private List<FeatureItem> features;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  TypeEnum value for type.
         * @param  features  List of FeatureItem value for features.
         */
        public Builder(TypeEnum type, List<FeatureItem> features) {
            this.type = type;
            this.features = features;
        }

        /**
         * Setter for type.
         * @param  type  TypeEnum value for type.
         * @return Builder
         */
        public Builder type(TypeEnum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for features.
         * @param  features  List of FeatureItem value for features.
         * @return Builder
         */
        public Builder features(List<FeatureItem> features) {
            this.features = features;
            return this;
        }

        /**
         * Builds a new {@link GeoFence} object using the set fields.
         * @return {@link GeoFence}
         */
        public GeoFence build() {
            return new GeoFence(type, features);
        }
    }
}
