/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for HeadingItem type.
 */
public class HeadingItem {
    private HeadingRange heading;

    /**
     * Default constructor.
     */
    public HeadingItem() {
    }

    /**
     * Initialization constructor.
     * @param  heading  HeadingRange value for heading.
     */
    @JsonCreator
    public HeadingItem(
            @JsonProperty("heading") HeadingRange heading) {
        this.heading = heading;
    }

    /**
     * Getter for Heading.
     * Acceptable heading range for road users in degrees.
     * @return Returns the HeadingRange
     */
    @JsonGetter("heading")
    public HeadingRange getHeading() {
        return heading;
    }

    /**
     * Setter for Heading.
     * Acceptable heading range for road users in degrees.
     * @param heading Value for HeadingRange
     */
    @JsonSetter("heading")
    public void setHeading(HeadingRange heading) {
        this.heading = heading;
    }

    /**
     * Converts this HeadingItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HeadingItem [" + "heading=" + heading + "]";
    }

    /**
     * Builds a new {@link HeadingItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HeadingItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(heading);
        return builder;
    }

    /**
     * Class to build instances of {@link HeadingItem}.
     */
    public static class Builder {
        private HeadingRange heading;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  heading  HeadingRange value for heading.
         */
        public Builder(HeadingRange heading) {
            this.heading = heading;
        }

        /**
         * Setter for heading.
         * @param  heading  HeadingRange value for heading.
         * @return Builder
         */
        public Builder heading(HeadingRange heading) {
            this.heading = heading;
            return this;
        }

        /**
         * Builds a new {@link HeadingItem} object using the set fields.
         * @return {@link HeadingItem}
         */
        public HeadingItem build() {
            return new HeadingItem(heading);
        }
    }
}
