/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ImpassabilityCauseCode type.
 */
public class ImpassabilityCauseCode {
    private int impassability5;

    /**
     * Default constructor.
     */
    public ImpassabilityCauseCode() {
    }

    /**
     * Initialization constructor.
     * @param  impassability5  int value for impassability5.
     */
    @JsonCreator
    public ImpassabilityCauseCode(
            @JsonProperty("impassability5") int impassability5) {
        this.impassability5 = impassability5;
    }

    /**
     * Getter for Impassability5.
     * The value shall be set to: - 0 `unavailable` - in case further detailed information about the
     * unmanaged road blockage is unavailable, - 1 `flooding ` - in case the road is affected by
     * flooding, - 2 `dangerOfAvalanches` - in case the road is at risk of being affected or blocked
     * by avalanches, - 3 `blastingOfAvalanches` - in case there is an active blasting of avalanches
     * on or near the road, - 4 `landslips` - in case the road is affected by landslips, - 5
     * `chemicalSpillage` - in case the road is affected by chemical spillage, - 6 `winterClosure` -
     * in case the road is impassable due to a winter closure. - 7 `sinkhole` - in case the road is
     * impassable due to large holes in the road surface. - 8 `earthquakeDamage` - in case the road
     * is obstructed or partially obstructed because of damage caused by an earthquake. - 9
     * `fallenTrees` - in case the road is obstructed or partially obstructed by one or more fallen
     * trees. - 10 `rockfalls` - in case the road is obstructed or partially obstructed due to
     * fallen rocks. - 11 `sewerOverflow` - in case the road is obstructed or partially obstructed
     * by overflows from one or more sewers. - 12 `stormDamage` - in case the road is obstructed or
     * partially obstructed by debris caused by strong winds. - 13 `subsidence` - in case the road
     * surface has sunken or collapsed in places. - 14 `burstPipe` - in case the road surface has
     * sunken or collapsed in places due to burst pipes. - 15 `burstWaterMain` - in case the road is
     * obstructed due to local flooding and/or subsidence. - 16 `fallenPowerCables` - in case the
     * road is obstructed or partly obstructed by one or more fallen power cables. - 17 `snowDrifts`
     * - in case the road is obstructed or partially obstructed by snow drifting in progress or
     * patches of deep snow due to earlier drifting. - 15-255 - are reserved for future usage.
     * @return Returns the int
     */
    @JsonGetter("impassability5")
    public int getImpassability5() {
        return impassability5;
    }

    /**
     * Setter for Impassability5.
     * The value shall be set to: - 0 `unavailable` - in case further detailed information about the
     * unmanaged road blockage is unavailable, - 1 `flooding ` - in case the road is affected by
     * flooding, - 2 `dangerOfAvalanches` - in case the road is at risk of being affected or blocked
     * by avalanches, - 3 `blastingOfAvalanches` - in case there is an active blasting of avalanches
     * on or near the road, - 4 `landslips` - in case the road is affected by landslips, - 5
     * `chemicalSpillage` - in case the road is affected by chemical spillage, - 6 `winterClosure` -
     * in case the road is impassable due to a winter closure. - 7 `sinkhole` - in case the road is
     * impassable due to large holes in the road surface. - 8 `earthquakeDamage` - in case the road
     * is obstructed or partially obstructed because of damage caused by an earthquake. - 9
     * `fallenTrees` - in case the road is obstructed or partially obstructed by one or more fallen
     * trees. - 10 `rockfalls` - in case the road is obstructed or partially obstructed due to
     * fallen rocks. - 11 `sewerOverflow` - in case the road is obstructed or partially obstructed
     * by overflows from one or more sewers. - 12 `stormDamage` - in case the road is obstructed or
     * partially obstructed by debris caused by strong winds. - 13 `subsidence` - in case the road
     * surface has sunken or collapsed in places. - 14 `burstPipe` - in case the road surface has
     * sunken or collapsed in places due to burst pipes. - 15 `burstWaterMain` - in case the road is
     * obstructed due to local flooding and/or subsidence. - 16 `fallenPowerCables` - in case the
     * road is obstructed or partly obstructed by one or more fallen power cables. - 17 `snowDrifts`
     * - in case the road is obstructed or partially obstructed by snow drifting in progress or
     * patches of deep snow due to earlier drifting. - 15-255 - are reserved for future usage.
     * @param impassability5 Value for int
     */
    @JsonSetter("impassability5")
    public void setImpassability5(int impassability5) {
        this.impassability5 = impassability5;
    }

    /**
     * Converts this ImpassabilityCauseCode into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ImpassabilityCauseCode [" + "impassability5=" + impassability5 + "]";
    }

    /**
     * Builds a new {@link ImpassabilityCauseCode.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ImpassabilityCauseCode.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(impassability5);
        return builder;
    }

    /**
     * Class to build instances of {@link ImpassabilityCauseCode}.
     */
    public static class Builder {
        private int impassability5;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  impassability5  int value for impassability5.
         */
        public Builder(int impassability5) {
            this.impassability5 = impassability5;
        }

        /**
         * Setter for impassability5.
         * @param  impassability5  int value for impassability5.
         * @return Builder
         */
        public Builder impassability5(int impassability5) {
            this.impassability5 = impassability5;
            return this;
        }

        /**
         * Builds a new {@link ImpassabilityCauseCode} object using the set fields.
         * @return {@link ImpassabilityCauseCode}
         */
        public ImpassabilityCauseCode build() {
            return new ImpassabilityCauseCode(impassability5);
        }
    }
}
