/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ITISItemWrapper type.
 */
public class ITISItemWrapper {
    private ITISItemContent item;

    /**
     * Default constructor.
     */
    public ITISItemWrapper() {
    }

    /**
     * Initialization constructor.
     * @param  item  ITISItemContent value for item.
     */
    @JsonCreator
    public ITISItemWrapper(
            @JsonProperty("item") ITISItemContent item) {
        this.item = item;
    }

    /**
     * Getter for Item.
     * An item object wrapping an ITIS code value.
     * @return Returns the ITISItemContent
     */
    @JsonGetter("item")
    public ITISItemContent getItem() {
        return item;
    }

    /**
     * Setter for Item.
     * An item object wrapping an ITIS code value.
     * @param item Value for ITISItemContent
     */
    @JsonSetter("item")
    public void setItem(ITISItemContent item) {
        this.item = item;
    }

    /**
     * Converts this ITISItemWrapper into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ITISItemWrapper [" + "item=" + item + "]";
    }

    /**
     * Builds a new {@link ITISItemWrapper.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ITISItemWrapper.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(item);
        return builder;
    }

    /**
     * Class to build instances of {@link ITISItemWrapper}.
     */
    public static class Builder {
        private ITISItemContent item;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  item  ITISItemContent value for item.
         */
        public Builder(ITISItemContent item) {
            this.item = item;
        }

        /**
         * Setter for item.
         * @param  item  ITISItemContent value for item.
         * @return Builder
         */
        public Builder item(ITISItemContent item) {
            this.item = item;
            return this;
        }

        /**
         * Builds a new {@link ITISItemWrapper} object using the set fields.
         * @return {@link ITISItemWrapper}
         */
        public ITISItemWrapper build() {
            return new ITISItemWrapper(item);
        }
    }
}
