/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PaginationFilter type.
 */
public class PaginationFilter {
    private String page;

    /**
     * Default constructor.
     */
    public PaginationFilter() {
    }

    /**
     * Initialization constructor.
     * @param  page  String value for page.
     */
    @JsonCreator
    public PaginationFilter(
            @JsonProperty("Page") String page) {
        this.page = page;
    }

    /**
     * Getter for Page.
     * Opaque pagination token for fetching the next/previous page of results. This is a encoded
     * string. Do not parse or modify; pass it as received.
     * @return Returns the String
     */
    @JsonGetter("Page")
    public String getPage() {
        return page;
    }

    /**
     * Setter for Page.
     * Opaque pagination token for fetching the next/previous page of results. This is a encoded
     * string. Do not parse or modify; pass it as received.
     * @param page Value for String
     */
    @JsonSetter("Page")
    public void setPage(String page) {
        this.page = page;
    }

    /**
     * Converts this PaginationFilter into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PaginationFilter [" + "page=" + page + "]";
    }

    /**
     * Builds a new {@link PaginationFilter.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PaginationFilter.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(page);
        return builder;
    }

    /**
     * Class to build instances of {@link PaginationFilter}.
     */
    public static class Builder {
        private String page;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  page  String value for page.
         */
        public Builder(String page) {
            this.page = page;
        }

        /**
         * Setter for page.
         * @param  page  String value for page.
         * @return Builder
         */
        public Builder page(String page) {
            this.page = page;
            return this;
        }

        /**
         * Builds a new {@link PaginationFilter} object using the set fields.
         * @return {@link PaginationFilter}
         */
        public PaginationFilter build() {
            return new PaginationFilter(page);
        }
    }
}
