/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PosConfidenceEllipse type.
 */
public class PosConfidenceEllipse {
    private int semiMajorConfidence;
    private int semiMinorConfidence;
    private int semiMajorOrientation;

    /**
     * Default constructor.
     */
    public PosConfidenceEllipse() {
    }

    /**
     * Initialization constructor.
     * @param  semiMajorConfidence  int value for semiMajorConfidence.
     * @param  semiMinorConfidence  int value for semiMinorConfidence.
     * @param  semiMajorOrientation  int value for semiMajorOrientation.
     */
    public PosConfidenceEllipse(
            int semiMajorConfidence,
            int semiMinorConfidence,
            int semiMajorOrientation) {
        this.semiMajorConfidence = semiMajorConfidence;
        this.semiMinorConfidence = semiMinorConfidence;
        this.semiMajorOrientation = semiMajorOrientation;
    }

    /**
     * Getter for SemiMajorConfidence.
     * Absolute position accuracy in one of the axis direction as defined in a shape of ellipse with
     * a predefined confidence level (set to 4095 when unavailable). The value shall be set to: -
     * `n` (`n &gt; 0` and `n &lt; 4094`) if the accuracy is equal to or less than n * 0,01 metre, -
     * `4094` if the accuracy is out of range, i.e. greater than 4,093 m, - `4095` if the accuracy
     * information is unavailable. The value 0 shall not be used.
     * @return Returns the int
     */
    @JsonGetter("semiMajorConfidence")
    public int getSemiMajorConfidence() {
        return semiMajorConfidence;
    }

    /**
     * Setter for SemiMajorConfidence.
     * Absolute position accuracy in one of the axis direction as defined in a shape of ellipse with
     * a predefined confidence level (set to 4095 when unavailable). The value shall be set to: -
     * `n` (`n &gt; 0` and `n &lt; 4094`) if the accuracy is equal to or less than n * 0,01 metre, -
     * `4094` if the accuracy is out of range, i.e. greater than 4,093 m, - `4095` if the accuracy
     * information is unavailable. The value 0 shall not be used.
     * @param semiMajorConfidence Value for int
     */
    @JsonSetter("semiMajorConfidence")
    public void setSemiMajorConfidence(int semiMajorConfidence) {
        this.semiMajorConfidence = semiMajorConfidence;
    }

    /**
     * Getter for SemiMinorConfidence.
     * Absolute position accuracy in one of the axis direction as defined in a shape of ellipse with
     * a predefined confidence level (set to 4095 when unavailable). The value shall be set to: -
     * `n` (`n &gt; 0` and `n &lt; 4094`) if the accuracy is equal to or less than n * 0,01 metre, -
     * `4094` if the accuracy is out of range, i.e. greater than 4,093 m, - `4095` if the accuracy
     * information is unavailable. The value 0 shall not be used.
     * @return Returns the int
     */
    @JsonGetter("semiMinorConfidence")
    public int getSemiMinorConfidence() {
        return semiMinorConfidence;
    }

    /**
     * Setter for SemiMinorConfidence.
     * Absolute position accuracy in one of the axis direction as defined in a shape of ellipse with
     * a predefined confidence level (set to 4095 when unavailable). The value shall be set to: -
     * `n` (`n &gt; 0` and `n &lt; 4094`) if the accuracy is equal to or less than n * 0,01 metre, -
     * `4094` if the accuracy is out of range, i.e. greater than 4,093 m, - `4095` if the accuracy
     * information is unavailable. The value 0 shall not be used.
     * @param semiMinorConfidence Value for int
     */
    @JsonSetter("semiMinorConfidence")
    public void setSemiMinorConfidence(int semiMinorConfidence) {
        this.semiMinorConfidence = semiMinorConfidence;
    }

    /**
     * Getter for SemiMajorOrientation.
     * An angle value in degrees described in the WGS84 reference system with respect to the WGS84
     * north. The value shall be set to: - wgs84North (0), - wgs84East (900), - wgs84South (1800), -
     * wgs84West (2700), - doNotUse (3600), - unavailable (3601)
     * @return Returns the int
     */
    @JsonGetter("semiMajorOrientation")
    public int getSemiMajorOrientation() {
        return semiMajorOrientation;
    }

    /**
     * Setter for SemiMajorOrientation.
     * An angle value in degrees described in the WGS84 reference system with respect to the WGS84
     * north. The value shall be set to: - wgs84North (0), - wgs84East (900), - wgs84South (1800), -
     * wgs84West (2700), - doNotUse (3600), - unavailable (3601)
     * @param semiMajorOrientation Value for int
     */
    @JsonSetter("semiMajorOrientation")
    public void setSemiMajorOrientation(int semiMajorOrientation) {
        this.semiMajorOrientation = semiMajorOrientation;
    }

    /**
     * Converts this PosConfidenceEllipse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PosConfidenceEllipse [" + "semiMajorConfidence=" + semiMajorConfidence
                + ", semiMinorConfidence=" + semiMinorConfidence + ", semiMajorOrientation="
                + semiMajorOrientation + "]";
    }

    /**
     * Builds a new {@link PosConfidenceEllipse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PosConfidenceEllipse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(semiMajorConfidence, semiMinorConfidence,
                semiMajorOrientation);
        return builder;
    }

    /**
     * Class to build instances of {@link PosConfidenceEllipse}.
     */
    public static class Builder {
        private int semiMajorConfidence;
        private int semiMinorConfidence;
        private int semiMajorOrientation;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  semiMajorConfidence  int value for semiMajorConfidence.
         * @param  semiMinorConfidence  int value for semiMinorConfidence.
         * @param  semiMajorOrientation  int value for semiMajorOrientation.
         */
        public Builder(int semiMajorConfidence, int semiMinorConfidence, int semiMajorOrientation) {
            this.semiMajorConfidence = semiMajorConfidence;
            this.semiMinorConfidence = semiMinorConfidence;
            this.semiMajorOrientation = semiMajorOrientation;
        }

        /**
         * Setter for semiMajorConfidence.
         * @param  semiMajorConfidence  int value for semiMajorConfidence.
         * @return Builder
         */
        public Builder semiMajorConfidence(int semiMajorConfidence) {
            this.semiMajorConfidence = semiMajorConfidence;
            return this;
        }

        /**
         * Setter for semiMinorConfidence.
         * @param  semiMinorConfidence  int value for semiMinorConfidence.
         * @return Builder
         */
        public Builder semiMinorConfidence(int semiMinorConfidence) {
            this.semiMinorConfidence = semiMinorConfidence;
            return this;
        }

        /**
         * Setter for semiMajorOrientation.
         * @param  semiMajorOrientation  int value for semiMajorOrientation.
         * @return Builder
         */
        public Builder semiMajorOrientation(int semiMajorOrientation) {
            this.semiMajorOrientation = semiMajorOrientation;
            return this;
        }

        /**
         * Builds a new {@link PosConfidenceEllipse} object using the set fields.
         * @return {@link PosConfidenceEllipse}
         */
        public PosConfidenceEllipse build() {
            return new PosConfidenceEllipse(semiMajorConfidence, semiMinorConfidence,
                    semiMajorOrientation);
        }
    }
}
