/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RegionIntersectionPair type.
 */
public class RegionIntersectionPair {
    private Integer regionId;
    private int intersectionId;

    /**
     * Default constructor.
     */
    public RegionIntersectionPair() {
        regionId = 0;
    }

    /**
     * Initialization constructor.
     * @param  intersectionId  int value for intersectionId.
     * @param  regionId  Integer value for regionId.
     */
    public RegionIntersectionPair(
            int intersectionId,
            Integer regionId) {
        this.regionId = regionId;
        this.intersectionId = intersectionId;
    }

    /**
     * Getter for RegionId.
     * The region identifier code (0-65535)
     * @return Returns the Integer
     */
    @JsonGetter("regionId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getRegionId() {
        return regionId;
    }

    /**
     * Setter for RegionId.
     * The region identifier code (0-65535)
     * @param regionId Value for Integer
     */
    @JsonSetter("regionId")
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * Getter for IntersectionId.
     * The intersection identifier code (0-65535)
     * @return Returns the int
     */
    @JsonGetter("intersectionId")
    public int getIntersectionId() {
        return intersectionId;
    }

    /**
     * Setter for IntersectionId.
     * The intersection identifier code (0-65535)
     * @param intersectionId Value for int
     */
    @JsonSetter("intersectionId")
    public void setIntersectionId(int intersectionId) {
        this.intersectionId = intersectionId;
    }

    /**
     * Converts this RegionIntersectionPair into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RegionIntersectionPair [" + "intersectionId=" + intersectionId + ", regionId="
                + regionId + "]";
    }

    /**
     * Builds a new {@link RegionIntersectionPair.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RegionIntersectionPair.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(intersectionId)
                .regionId(getRegionId());
        return builder;
    }

    /**
     * Class to build instances of {@link RegionIntersectionPair}.
     */
    public static class Builder {
        private int intersectionId;
        private Integer regionId = 0;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  intersectionId  int value for intersectionId.
         */
        public Builder(int intersectionId) {
            this.intersectionId = intersectionId;
        }

        /**
         * Setter for intersectionId.
         * @param  intersectionId  int value for intersectionId.
         * @return Builder
         */
        public Builder intersectionId(int intersectionId) {
            this.intersectionId = intersectionId;
            return this;
        }

        /**
         * Setter for regionId.
         * @param  regionId  Integer value for regionId.
         * @return Builder
         */
        public Builder regionId(Integer regionId) {
            this.regionId = regionId;
            return this;
        }

        /**
         * Builds a new {@link RegionIntersectionPair} object using the set fields.
         * @return {@link RegionIntersectionPair}
         */
        public RegionIntersectionPair build() {
            return new RegionIntersectionPair(intersectionId, regionId);
        }
    }
}
