/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RoadSignMsgId type.
 */
public class RoadSignMsgId {
    private RoadSignID roadSignID;

    /**
     * Default constructor.
     */
    public RoadSignMsgId() {
    }

    /**
     * Initialization constructor.
     * @param  roadSignID  RoadSignID value for roadSignID.
     */
    @JsonCreator
    public RoadSignMsgId(
            @JsonProperty("roadSignID") RoadSignID roadSignID) {
        this.roadSignID = roadSignID;
    }

    /**
     * Getter for RoadSignID.
     * It provide a precise location of one or more roadside signs.
     * @return Returns the RoadSignID
     */
    @JsonGetter("roadSignID")
    public RoadSignID getRoadSignID() {
        return roadSignID;
    }

    /**
     * Setter for RoadSignID.
     * It provide a precise location of one or more roadside signs.
     * @param roadSignID Value for RoadSignID
     */
    @JsonSetter("roadSignID")
    public void setRoadSignID(RoadSignID roadSignID) {
        this.roadSignID = roadSignID;
    }

    /**
     * Converts this RoadSignMsgId into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RoadSignMsgId [" + "roadSignID=" + roadSignID + "]";
    }

    /**
     * Builds a new {@link RoadSignMsgId.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RoadSignMsgId.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(roadSignID);
        return builder;
    }

    /**
     * Class to build instances of {@link RoadSignMsgId}.
     */
    public static class Builder {
        private RoadSignID roadSignID;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  roadSignID  RoadSignID value for roadSignID.
         */
        public Builder(RoadSignID roadSignID) {
            this.roadSignID = roadSignID;
        }

        /**
         * Setter for roadSignID.
         * @param  roadSignID  RoadSignID value for roadSignID.
         * @return Builder
         */
        public Builder roadSignID(RoadSignID roadSignID) {
            this.roadSignID = roadSignID;
            return this;
        }

        /**
         * Builds a new {@link RoadSignMsgId} object using the set fields.
         * @return {@link RoadSignMsgId}
         */
        public RoadSignMsgId build() {
            return new RoadSignMsgId(roadSignID);
        }
    }
}
