/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SaeAlertMessage type.
 */
public class SaeAlertMessage {
    private SaeAlertPayload saeAlert;

    /**
     * Default constructor.
     */
    public SaeAlertMessage() {
    }

    /**
     * Initialization constructor.
     * @param  saeAlert  SaeAlertPayload value for saeAlert.
     */
    public SaeAlertMessage(
            SaeAlertPayload saeAlert) {
        this.saeAlert = saeAlert;
    }

    /**
     * Getter for SaeAlert.
     * Road Side Alert (RSA) message payload as defined in SAE J2735.
     * @return Returns the SaeAlertPayload
     */
    @JsonGetter("saeAlert")
    public SaeAlertPayload getSaeAlert() {
        return saeAlert;
    }

    /**
     * Setter for SaeAlert.
     * Road Side Alert (RSA) message payload as defined in SAE J2735.
     * @param saeAlert Value for SaeAlertPayload
     */
    @JsonSetter("saeAlert")
    public void setSaeAlert(SaeAlertPayload saeAlert) {
        this.saeAlert = saeAlert;
    }

    /**
     * Converts this SaeAlertMessage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SaeAlertMessage [" + "saeAlert=" + saeAlert + "]";
    }

    /**
     * Builds a new {@link SaeAlertMessage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SaeAlertMessage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(saeAlert);
        return builder;
    }

    /**
     * Class to build instances of {@link SaeAlertMessage}.
     */
    public static class Builder {
        private SaeAlertPayload saeAlert;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  saeAlert  SaeAlertPayload value for saeAlert.
         */
        public Builder(SaeAlertPayload saeAlert) {
            this.saeAlert = saeAlert;
        }

        /**
         * Setter for saeAlert.
         * @param  saeAlert  SaeAlertPayload value for saeAlert.
         * @return Builder
         */
        public Builder saeAlert(SaeAlertPayload saeAlert) {
            this.saeAlert = saeAlert;
            return this;
        }

        /**
         * Builds a new {@link SaeAlertMessage} object using the set fields.
         * @return {@link SaeAlertMessage}
         */
        public SaeAlertMessage build() {
            return new SaeAlertMessage(saeAlert);
        }
    }
}
