/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SaeInfoMessage type.
 */
public class SaeInfoMessage {
    private SaeInfoPayload saeInfo;

    /**
     * Default constructor.
     */
    public SaeInfoMessage() {
    }

    /**
     * Initialization constructor.
     * @param  saeInfo  SaeInfoPayload value for saeInfo.
     */
    public SaeInfoMessage(
            SaeInfoPayload saeInfo) {
        this.saeInfo = saeInfo;
    }

    /**
     * Getter for SaeInfo.
     * Traveler Information Message (TIM) payload as defined in SAE J2735.
     * @return Returns the SaeInfoPayload
     */
    @JsonGetter("saeInfo")
    public SaeInfoPayload getSaeInfo() {
        return saeInfo;
    }

    /**
     * Setter for SaeInfo.
     * Traveler Information Message (TIM) payload as defined in SAE J2735.
     * @param saeInfo Value for SaeInfoPayload
     */
    @JsonSetter("saeInfo")
    public void setSaeInfo(SaeInfoPayload saeInfo) {
        this.saeInfo = saeInfo;
    }

    /**
     * Converts this SaeInfoMessage into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SaeInfoMessage [" + "saeInfo=" + saeInfo + "]";
    }

    /**
     * Builds a new {@link SaeInfoMessage.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SaeInfoMessage.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(saeInfo);
        return builder;
    }

    /**
     * Class to build instances of {@link SaeInfoMessage}.
     */
    public static class Builder {
        private SaeInfoPayload saeInfo;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  saeInfo  SaeInfoPayload value for saeInfo.
         */
        public Builder(SaeInfoPayload saeInfo) {
            this.saeInfo = saeInfo;
        }

        /**
         * Setter for saeInfo.
         * @param  saeInfo  SaeInfoPayload value for saeInfo.
         * @return Builder
         */
        public Builder saeInfo(SaeInfoPayload saeInfo) {
            this.saeInfo = saeInfo;
            return this;
        }

        /**
         * Builds a new {@link SaeInfoMessage} object using the set fields.
         * @return {@link SaeInfoMessage}
         */
        public SaeInfoMessage build() {
            return new SaeInfoMessage(saeInfo);
        }
    }
}
