/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SpeedItem type.
 */
public class SpeedItem {
    private SpeedRange speed;

    /**
     * Default constructor.
     */
    public SpeedItem() {
    }

    /**
     * Initialization constructor.
     * @param  speed  SpeedRange value for speed.
     */
    @JsonCreator
    public SpeedItem(
            @JsonProperty("speed") SpeedRange speed) {
        this.speed = speed;
    }

    /**
     * Getter for Speed.
     * Acceptable speed range for road users in m/s.
     * @return Returns the SpeedRange
     */
    @JsonGetter("speed")
    public SpeedRange getSpeed() {
        return speed;
    }

    /**
     * Setter for Speed.
     * Acceptable speed range for road users in m/s.
     * @param speed Value for SpeedRange
     */
    @JsonSetter("speed")
    public void setSpeed(SpeedRange speed) {
        this.speed = speed;
    }

    /**
     * Converts this SpeedItem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SpeedItem [" + "speed=" + speed + "]";
    }

    /**
     * Builds a new {@link SpeedItem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SpeedItem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(speed);
        return builder;
    }

    /**
     * Class to build instances of {@link SpeedItem}.
     */
    public static class Builder {
        private SpeedRange speed;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  speed  SpeedRange value for speed.
         */
        public Builder(SpeedRange speed) {
            this.speed = speed;
        }

        /**
         * Setter for speed.
         * @param  speed  SpeedRange value for speed.
         * @return Builder
         */
        public Builder speed(SpeedRange speed) {
            this.speed = speed;
            return this;
        }

        /**
         * Builds a new {@link SpeedItem} object using the set fields.
         * @return {@link SpeedItem}
         */
        public SpeedItem build() {
            return new SpeedItem(speed);
        }
    }
}
