/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.thingspace.models.containers.TextPhraseOrITIS;
import java.util.List;

/**
 * This is a model class for SpeedLimitContent type.
 */
public class SpeedLimitContent {
    private List<TextPhraseOrITIS> speedLimit;

    /**
     * Default constructor.
     */
    public SpeedLimitContent() {
    }

    /**
     * Initialization constructor.
     * @param  speedLimit  List of TextPhraseOrITIS value for speedLimit.
     */
    @JsonCreator
    public SpeedLimitContent(
            @JsonProperty("speedLimit") List<TextPhraseOrITIS> speedLimit) {
        this.speedLimit = speedLimit;
    }

    /**
     * Getter for SpeedLimit.
     * List of speed limits and cautions.
     * @return Returns the List of TextPhraseOrITIS
     */
    @JsonGetter("speedLimit")
    public List<TextPhraseOrITIS> getSpeedLimit() {
        return speedLimit;
    }

    /**
     * Setter for SpeedLimit.
     * List of speed limits and cautions.
     * @param speedLimit Value for List of TextPhraseOrITIS
     */
    @JsonSetter("speedLimit")
    public void setSpeedLimit(List<TextPhraseOrITIS> speedLimit) {
        this.speedLimit = speedLimit;
    }

    /**
     * Converts this SpeedLimitContent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SpeedLimitContent [" + "speedLimit=" + speedLimit + "]";
    }

    /**
     * Builds a new {@link SpeedLimitContent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SpeedLimitContent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(speedLimit);
        return builder;
    }

    /**
     * Class to build instances of {@link SpeedLimitContent}.
     */
    public static class Builder {
        private List<TextPhraseOrITIS> speedLimit;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  speedLimit  List of TextPhraseOrITIS value for speedLimit.
         */
        public Builder(List<TextPhraseOrITIS> speedLimit) {
            this.speedLimit = speedLimit;
        }

        /**
         * Setter for speedLimit.
         * @param  speedLimit  List of TextPhraseOrITIS value for speedLimit.
         * @return Builder
         */
        public Builder speedLimit(List<TextPhraseOrITIS> speedLimit) {
            this.speedLimit = speedLimit;
            return this;
        }

        /**
         * Builds a new {@link SpeedLimitContent} object using the set fields.
         * @return {@link SpeedLimitContent}
         */
        public SpeedLimitContent build() {
            return new SpeedLimitContent(speedLimit);
        }
    }
}
