/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TextPhraseItemContent type.
 */
public class TextPhraseItemContent {
    private String text;

    /**
     * Default constructor.
     */
    public TextPhraseItemContent() {
    }

    /**
     * Initialization constructor.
     * @param  text  String value for text.
     */
    public TextPhraseItemContent(
            String text) {
        this.text = text;
    }

    /**
     * Getter for Text.
     * Text phrase provides very short sections of text interspersed between the ITIS codes to
     * create phrases. In general, this is used for expressing proper nouns, such as street names
     * reflecting local expressions that do not appear in the ITIS tables.
     * @return Returns the String
     */
    @JsonGetter("text")
    public String getText() {
        return text;
    }

    /**
     * Setter for Text.
     * Text phrase provides very short sections of text interspersed between the ITIS codes to
     * create phrases. In general, this is used for expressing proper nouns, such as street names
     * reflecting local expressions that do not appear in the ITIS tables.
     * @param text Value for String
     */
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Converts this TextPhraseItemContent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TextPhraseItemContent [" + "text=" + text + "]";
    }

    /**
     * Builds a new {@link TextPhraseItemContent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TextPhraseItemContent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(text);
        return builder;
    }

    /**
     * Class to build instances of {@link TextPhraseItemContent}.
     */
    public static class Builder {
        private String text;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  text  String value for text.
         */
        public Builder(String text) {
            this.text = text;
        }

        /**
         * Setter for text.
         * @param  text  String value for text.
         * @return Builder
         */
        public Builder text(String text) {
            this.text = text;
            return this;
        }

        /**
         * Builds a new {@link TextPhraseItemContent} object using the set fields.
         * @return {@link TextPhraseItemContent}
         */
        public TextPhraseItemContent build() {
            return new TextPhraseItemContent(text);
        }
    }
}
