/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TextItemContent type.
 */
public class TextItemContent {
    private String text;

    /**
     * Default constructor.
     */
    public TextItemContent() {
    }

    /**
     * Initialization constructor.
     * @param  text  String value for text.
     */
    public TextItemContent(
            String text) {
        this.text = text;
    }

    /**
     * Getter for Text.
     * Simple text used with ITIS codes. (Text taken from SAE J2540.)
     * @return Returns the String
     */
    @JsonGetter("text")
    public String getText() {
        return text;
    }

    /**
     * Setter for Text.
     * Simple text used with ITIS codes. (Text taken from SAE J2540.)
     * @param text Value for String
     */
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }

    /**
     * Converts this TextItemContent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TextItemContent [" + "text=" + text + "]";
    }

    /**
     * Builds a new {@link TextItemContent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TextItemContent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(text);
        return builder;
    }

    /**
     * Class to build instances of {@link TextItemContent}.
     */
    public static class Builder {
        private String text;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  text  String value for text.
         */
        public Builder(String text) {
            this.text = text;
        }

        /**
         * Setter for text.
         * @param  text  String value for text.
         * @return Builder
         */
        public Builder text(String text) {
            this.text = text;
            return this;
        }

        /**
         * Builds a new {@link TextItemContent} object using the set fields.
         * @return {@link TextItemContent}
         */
        public TextItemContent build() {
            return new TextItemContent(text);
        }
    }
}
