/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TextItemWrapper type.
 */
public class TextItemWrapper {
    private TextItemContent item;

    /**
     * Default constructor.
     */
    public TextItemWrapper() {
    }

    /**
     * Initialization constructor.
     * @param  item  TextItemContent value for item.
     */
    @JsonCreator
    public TextItemWrapper(
            @JsonProperty("item") TextItemContent item) {
        this.item = item;
    }

    /**
     * Getter for Item.
     * An item object wrapping a text value.
     * @return Returns the TextItemContent
     */
    @JsonGetter("item")
    public TextItemContent getItem() {
        return item;
    }

    /**
     * Setter for Item.
     * An item object wrapping a text value.
     * @param item Value for TextItemContent
     */
    @JsonSetter("item")
    public void setItem(TextItemContent item) {
        this.item = item;
    }

    /**
     * Converts this TextItemWrapper into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TextItemWrapper [" + "item=" + item + "]";
    }

    /**
     * Builds a new {@link TextItemWrapper.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TextItemWrapper.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(item);
        return builder;
    }

    /**
     * Class to build instances of {@link TextItemWrapper}.
     */
    public static class Builder {
        private TextItemContent item;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  item  TextItemContent value for item.
         */
        public Builder(TextItemContent item) {
            this.item = item;
        }

        /**
         * Setter for item.
         * @param  item  TextItemContent value for item.
         * @return Builder
         */
        public Builder item(TextItemContent item) {
            this.item = item;
            return this;
        }

        /**
         * Builds a new {@link TextItemWrapper} object using the set fields.
         * @return {@link TextItemWrapper}
         */
        public TextItemWrapper build() {
            return new TextItemWrapper(item);
        }
    }
}
