/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TextPhraseItemWrapper type.
 */
public class TextPhraseItemWrapper {
    private TextPhraseItemContent item;

    /**
     * Default constructor.
     */
    public TextPhraseItemWrapper() {
    }

    /**
     * Initialization constructor.
     * @param  item  TextPhraseItemContent value for item.
     */
    @JsonCreator
    public TextPhraseItemWrapper(
            @JsonProperty("item") TextPhraseItemContent item) {
        this.item = item;
    }

    /**
     * Getter for Item.
     * An item object wrapping a text phrase value.
     * @return Returns the TextPhraseItemContent
     */
    @JsonGetter("item")
    public TextPhraseItemContent getItem() {
        return item;
    }

    /**
     * Setter for Item.
     * An item object wrapping a text phrase value.
     * @param item Value for TextPhraseItemContent
     */
    @JsonSetter("item")
    public void setItem(TextPhraseItemContent item) {
        this.item = item;
    }

    /**
     * Converts this TextPhraseItemWrapper into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TextPhraseItemWrapper [" + "item=" + item + "]";
    }

    /**
     * Builds a new {@link TextPhraseItemWrapper.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TextPhraseItemWrapper.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(item);
        return builder;
    }

    /**
     * Class to build instances of {@link TextPhraseItemWrapper}.
     */
    public static class Builder {
        private TextPhraseItemContent item;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  item  TextPhraseItemContent value for item.
         */
        public Builder(TextPhraseItemContent item) {
            this.item = item;
        }

        /**
         * Setter for item.
         * @param  item  TextPhraseItemContent value for item.
         * @return Builder
         */
        public Builder item(TextPhraseItemContent item) {
            this.item = item;
            return this;
        }

        /**
         * Builds a new {@link TextPhraseItemWrapper} object using the set fields.
         * @return {@link TextPhraseItemWrapper}
         */
        public TextPhraseItemWrapper build() {
            return new TextPhraseItemWrapper(item);
        }
    }
}
