/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.thingspace.models.containers.TextPhraseOrITIS;
import java.util.List;

/**
 * This is a model class for WorkZoneContent type.
 */
public class WorkZoneContent {
    private List<TextPhraseOrITIS> workZone;

    /**
     * Default constructor.
     */
    public WorkZoneContent() {
    }

    /**
     * Initialization constructor.
     * @param  workZone  List of TextPhraseOrITIS value for workZone.
     */
    @JsonCreator
    public WorkZoneContent(
            @JsonProperty("workZone") List<TextPhraseOrITIS> workZone) {
        this.workZone = workZone;
    }

    /**
     * Getter for WorkZone.
     * List of work zone signs and directions.
     * @return Returns the List of TextPhraseOrITIS
     */
    @JsonGetter("workZone")
    public List<TextPhraseOrITIS> getWorkZone() {
        return workZone;
    }

    /**
     * Setter for WorkZone.
     * List of work zone signs and directions.
     * @param workZone Value for List of TextPhraseOrITIS
     */
    @JsonSetter("workZone")
    public void setWorkZone(List<TextPhraseOrITIS> workZone) {
        this.workZone = workZone;
    }

    /**
     * Converts this WorkZoneContent into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "WorkZoneContent [" + "workZone=" + workZone + "]";
    }

    /**
     * Builds a new {@link WorkZoneContent.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link WorkZoneContent.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(workZone);
        return builder;
    }

    /**
     * Class to build instances of {@link WorkZoneContent}.
     */
    public static class Builder {
        private List<TextPhraseOrITIS> workZone;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  workZone  List of TextPhraseOrITIS value for workZone.
         */
        public Builder(List<TextPhraseOrITIS> workZone) {
            this.workZone = workZone;
        }

        /**
         * Setter for workZone.
         * @param  workZone  List of TextPhraseOrITIS value for workZone.
         * @return Builder
         */
        public Builder workZone(List<TextPhraseOrITIS> workZone) {
            this.workZone = workZone;
            return this;
        }

        /**
         * Builds a new {@link WorkZoneContent} object using the set fields.
         * @return {@link WorkZoneContent}
         */
        public WorkZoneContent build() {
            return new WorkZoneContent(workZone);
        }
    }
}
