/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for WrongWayDrivingCauseCode type.
 */
public class WrongWayDrivingCauseCode {
    private int wrongWayDriving14;

    /**
     * Default constructor.
     */
    public WrongWayDrivingCauseCode() {
    }

    /**
     * Initialization constructor.
     * @param  wrongWayDriving14  int value for wrongWayDriving14.
     */
    @JsonCreator
    public WrongWayDrivingCauseCode(
            @JsonProperty("wrongWayDriving14") int wrongWayDriving14) {
        this.wrongWayDriving14 = wrongWayDriving14;
    }

    /**
     * Getter for WrongWayDriving14.
     * The value shall be set to: - 0 `unavailable` - in case further detailed information on wrong
     * way driving event is unavailable, - 1 `wrongLane` - in case vehicle is driving on a lane for
     * which it has no authorization to use, - 2 `wrongDirection` - in case vehicle is driving in a
     * direction that it is not allowed, - 3-255 - reserved for future usage.
     * @return Returns the int
     */
    @JsonGetter("wrongWayDriving14")
    public int getWrongWayDriving14() {
        return wrongWayDriving14;
    }

    /**
     * Setter for WrongWayDriving14.
     * The value shall be set to: - 0 `unavailable` - in case further detailed information on wrong
     * way driving event is unavailable, - 1 `wrongLane` - in case vehicle is driving on a lane for
     * which it has no authorization to use, - 2 `wrongDirection` - in case vehicle is driving in a
     * direction that it is not allowed, - 3-255 - reserved for future usage.
     * @param wrongWayDriving14 Value for int
     */
    @JsonSetter("wrongWayDriving14")
    public void setWrongWayDriving14(int wrongWayDriving14) {
        this.wrongWayDriving14 = wrongWayDriving14;
    }

    /**
     * Converts this WrongWayDrivingCauseCode into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "WrongWayDrivingCauseCode [" + "wrongWayDriving14=" + wrongWayDriving14 + "]";
    }

    /**
     * Builds a new {@link WrongWayDrivingCauseCode.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link WrongWayDrivingCauseCode.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(wrongWayDriving14);
        return builder;
    }

    /**
     * Class to build instances of {@link WrongWayDrivingCauseCode}.
     */
    public static class Builder {
        private int wrongWayDriving14;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  wrongWayDriving14  int value for wrongWayDriving14.
         */
        public Builder(int wrongWayDriving14) {
            this.wrongWayDriving14 = wrongWayDriving14;
        }

        /**
         * Setter for wrongWayDriving14.
         * @param  wrongWayDriving14  int value for wrongWayDriving14.
         * @return Builder
         */
        public Builder wrongWayDriving14(int wrongWayDriving14) {
            this.wrongWayDriving14 = wrongWayDriving14;
            return this;
        }

        /**
         * Builds a new {@link WrongWayDrivingCauseCode} object using the set fields.
         * @return {@link WrongWayDrivingCauseCode}
         */
        public WrongWayDrivingCauseCode build() {
            return new WrongWayDrivingCauseCode(wrongWayDriving14);
        }
    }
}
