/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.verizon.thingspace.ApiHelper;
import com.verizon.thingspace.models.ITISItemWrapper;
import com.verizon.thingspace.models.TextItemWrapper;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = AdvisoryItem.AdvisoryItemDeserializer.class)
public abstract class AdvisoryItem {
    
    /**
     * This is ITISItemWrapper case.
     * @param iTISItemWrapper ITISItemWrapper value for iTISItemWrapper.
     * @return The ITISItemWrapperCase object.
     */
    public static AdvisoryItem fromITISItemWrapper(ITISItemWrapper iTISItemWrapper) {
        return iTISItemWrapper == null ? null : new ITISItemWrapperCase(iTISItemWrapper);
    }

    /**
     * This is TextItemWrapper case.
     * @param textItemWrapper TextItemWrapper value for textItemWrapper.
     * @return The TextItemWrapperCase object.
     */
    public static AdvisoryItem fromTextItemWrapper(TextItemWrapper textItemWrapper) {
        return textItemWrapper == null ? null : new TextItemWrapperCase(textItemWrapper);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R iTISItemWrapper(ITISItemWrapper iTISItemWrapper);

        R textItemWrapper(TextItemWrapper textItemWrapper);
    }

    /**
     * This is a implementation class for ITISItemWrapperCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "ITISItemWrapper")
    private static class ITISItemWrapperCase extends AdvisoryItem {

        @JsonValue
        private ITISItemWrapper iTISItemWrapper;

        ITISItemWrapperCase(ITISItemWrapper iTISItemWrapper) {
            this.iTISItemWrapper = iTISItemWrapper;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.iTISItemWrapper(this.iTISItemWrapper);
        }

        @JsonCreator
        private ITISItemWrapperCase(JsonNode jsonNode) throws IOException {
            this.iTISItemWrapper = ApiHelper.deserialize(jsonNode,
                ITISItemWrapper.class);
        }

        @Override
        public String toString() {
            return iTISItemWrapper.toString();
        }
    }

    /**
     * This is a implementation class for TextItemWrapperCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "TextItemWrapper")
    private static class TextItemWrapperCase extends AdvisoryItem {

        @JsonValue
        private TextItemWrapper textItemWrapper;

        TextItemWrapperCase(TextItemWrapper textItemWrapper) {
            this.textItemWrapper = textItemWrapper;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.textItemWrapper(this.textItemWrapper);
        }

        @JsonCreator
        private TextItemWrapperCase(JsonNode jsonNode) throws IOException {
            this.textItemWrapper = ApiHelper.deserialize(jsonNode,
                TextItemWrapper.class);
        }

        @Override
        public String toString() {
            return textItemWrapper.toString();
        }
    }

    /**
     * This is a custom deserializer class for AdvisoryItem.
     */
    protected static class AdvisoryItemDeserializer
            extends JsonDeserializer<AdvisoryItem> {

        @Override
        public AdvisoryItem deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(ITISItemWrapperCase.class,
                    TextItemWrapperCase.class), true);
        }
    }

}
