/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.verizon.thingspace.ApiHelper;
import com.verizon.thingspace.models.AccidentCauseCode;
import com.verizon.thingspace.models.EmergencyVehicleApproachingCauseCode;
import com.verizon.thingspace.models.ImpassabilityCauseCode;
import com.verizon.thingspace.models.RoadworksCauseCode;
import com.verizon.thingspace.models.TrafficConditionCauseCode;
import com.verizon.thingspace.models.WrongWayDrivingCauseCode;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = CauseCodeChoice.CauseCodeChoiceDeserializer.class)
public abstract class CauseCodeChoice {
    
    /**
     * This is TrafficConditionCauseCode case.
     * @param trafficConditionCauseCode TrafficConditionCauseCode value for trafficConditionCauseCode.
     * @return The TrafficConditionCauseCodeCase object.
     */
    public static CauseCodeChoice fromTrafficConditionCauseCode(
            TrafficConditionCauseCode trafficConditionCauseCode) {
        return trafficConditionCauseCode == null ? null : new TrafficConditionCauseCodeCase(trafficConditionCauseCode);
    }

    /**
     * This is AccidentCauseCode case.
     * @param accidentCauseCode AccidentCauseCode value for accidentCauseCode.
     * @return The AccidentCauseCodeCase object.
     */
    public static CauseCodeChoice fromAccidentCauseCode(AccidentCauseCode accidentCauseCode) {
        return accidentCauseCode == null ? null : new AccidentCauseCodeCase(accidentCauseCode);
    }

    /**
     * This is RoadworksCauseCode case.
     * @param roadworksCauseCode RoadworksCauseCode value for roadworksCauseCode.
     * @return The RoadworksCauseCodeCase object.
     */
    public static CauseCodeChoice fromRoadworksCauseCode(RoadworksCauseCode roadworksCauseCode) {
        return roadworksCauseCode == null ? null : new RoadworksCauseCodeCase(roadworksCauseCode);
    }

    /**
     * This is ImpassabilityCauseCode case.
     * @param impassabilityCauseCode ImpassabilityCauseCode value for impassabilityCauseCode.
     * @return The ImpassabilityCauseCodeCase object.
     */
    public static CauseCodeChoice fromImpassabilityCauseCode(
            ImpassabilityCauseCode impassabilityCauseCode) {
        return impassabilityCauseCode == null ? null : new ImpassabilityCauseCodeCase(impassabilityCauseCode);
    }

    /**
     * This is WrongWayDrivingCauseCode case.
     * @param wrongWayDrivingCauseCode WrongWayDrivingCauseCode value for wrongWayDrivingCauseCode.
     * @return The WrongWayDrivingCauseCodeCase object.
     */
    public static CauseCodeChoice fromWrongWayDrivingCauseCode(
            WrongWayDrivingCauseCode wrongWayDrivingCauseCode) {
        return wrongWayDrivingCauseCode == null ? null : new WrongWayDrivingCauseCodeCase(wrongWayDrivingCauseCode);
    }

    /**
     * This is EmergencyVehicleApproachingCauseCode case.
     * @param emergencyVehicleApproachingCauseCode EmergencyVehicleApproachingCauseCode value for emergencyVehicleApproachingCauseCode.
     * @return The EmergencyVehicleApproachingCauseCodeCase object.
     */
    public static CauseCodeChoice fromEmergencyVehicleApproachingCauseCode(
            EmergencyVehicleApproachingCauseCode emergencyVehicleApproachingCauseCode) {
        return emergencyVehicleApproachingCauseCode == null ? null : new EmergencyVehicleApproachingCauseCodeCase(emergencyVehicleApproachingCauseCode);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R trafficConditionCauseCode(TrafficConditionCauseCode trafficConditionCauseCode);

        R accidentCauseCode(AccidentCauseCode accidentCauseCode);

        R roadworksCauseCode(RoadworksCauseCode roadworksCauseCode);

        R impassabilityCauseCode(ImpassabilityCauseCode impassabilityCauseCode);

        R wrongWayDrivingCauseCode(WrongWayDrivingCauseCode wrongWayDrivingCauseCode);

        R emergencyVehicleApproachingCauseCode(EmergencyVehicleApproachingCauseCode emergencyVehicleApproachingCauseCode);
    }

    /**
     * This is a implementation class for TrafficConditionCauseCodeCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "TrafficConditionCauseCode")
    private static class TrafficConditionCauseCodeCase extends CauseCodeChoice {

        @JsonValue
        private TrafficConditionCauseCode trafficConditionCauseCode;

        TrafficConditionCauseCodeCase(TrafficConditionCauseCode trafficConditionCauseCode) {
            this.trafficConditionCauseCode = trafficConditionCauseCode;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.trafficConditionCauseCode(this.trafficConditionCauseCode);
        }

        @JsonCreator
        private TrafficConditionCauseCodeCase(JsonNode jsonNode) throws IOException {
            this.trafficConditionCauseCode = ApiHelper.deserialize(jsonNode,
                TrafficConditionCauseCode.class);
        }

        @Override
        public String toString() {
            return trafficConditionCauseCode.toString();
        }
    }

    /**
     * This is a implementation class for AccidentCauseCodeCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "AccidentCauseCode")
    private static class AccidentCauseCodeCase extends CauseCodeChoice {

        @JsonValue
        private AccidentCauseCode accidentCauseCode;

        AccidentCauseCodeCase(AccidentCauseCode accidentCauseCode) {
            this.accidentCauseCode = accidentCauseCode;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.accidentCauseCode(this.accidentCauseCode);
        }

        @JsonCreator
        private AccidentCauseCodeCase(JsonNode jsonNode) throws IOException {
            this.accidentCauseCode = ApiHelper.deserialize(jsonNode,
                AccidentCauseCode.class);
        }

        @Override
        public String toString() {
            return accidentCauseCode.toString();
        }
    }

    /**
     * This is a implementation class for RoadworksCauseCodeCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "RoadworksCauseCode")
    private static class RoadworksCauseCodeCase extends CauseCodeChoice {

        @JsonValue
        private RoadworksCauseCode roadworksCauseCode;

        RoadworksCauseCodeCase(RoadworksCauseCode roadworksCauseCode) {
            this.roadworksCauseCode = roadworksCauseCode;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.roadworksCauseCode(this.roadworksCauseCode);
        }

        @JsonCreator
        private RoadworksCauseCodeCase(JsonNode jsonNode) throws IOException {
            this.roadworksCauseCode = ApiHelper.deserialize(jsonNode,
                RoadworksCauseCode.class);
        }

        @Override
        public String toString() {
            return roadworksCauseCode.toString();
        }
    }

    /**
     * This is a implementation class for ImpassabilityCauseCodeCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "ImpassabilityCauseCode")
    private static class ImpassabilityCauseCodeCase extends CauseCodeChoice {

        @JsonValue
        private ImpassabilityCauseCode impassabilityCauseCode;

        ImpassabilityCauseCodeCase(ImpassabilityCauseCode impassabilityCauseCode) {
            this.impassabilityCauseCode = impassabilityCauseCode;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.impassabilityCauseCode(this.impassabilityCauseCode);
        }

        @JsonCreator
        private ImpassabilityCauseCodeCase(JsonNode jsonNode) throws IOException {
            this.impassabilityCauseCode = ApiHelper.deserialize(jsonNode,
                ImpassabilityCauseCode.class);
        }

        @Override
        public String toString() {
            return impassabilityCauseCode.toString();
        }
    }

    /**
     * This is a implementation class for WrongWayDrivingCauseCodeCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "WrongWayDrivingCauseCode")
    private static class WrongWayDrivingCauseCodeCase extends CauseCodeChoice {

        @JsonValue
        private WrongWayDrivingCauseCode wrongWayDrivingCauseCode;

        WrongWayDrivingCauseCodeCase(WrongWayDrivingCauseCode wrongWayDrivingCauseCode) {
            this.wrongWayDrivingCauseCode = wrongWayDrivingCauseCode;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.wrongWayDrivingCauseCode(this.wrongWayDrivingCauseCode);
        }

        @JsonCreator
        private WrongWayDrivingCauseCodeCase(JsonNode jsonNode) throws IOException {
            this.wrongWayDrivingCauseCode = ApiHelper.deserialize(jsonNode,
                WrongWayDrivingCauseCode.class);
        }

        @Override
        public String toString() {
            return wrongWayDrivingCauseCode.toString();
        }
    }

    /**
     * This is a implementation class for EmergencyVehicleApproachingCauseCodeCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "EmergencyVehicleApproachingCauseCode")
    private static class EmergencyVehicleApproachingCauseCodeCase extends CauseCodeChoice {

        @JsonValue
        private EmergencyVehicleApproachingCauseCode emergencyVehicleApproachingCauseCode;

        EmergencyVehicleApproachingCauseCodeCase(EmergencyVehicleApproachingCauseCode emergencyVehicleApproachingCauseCode) {
            this.emergencyVehicleApproachingCauseCode = emergencyVehicleApproachingCauseCode;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.emergencyVehicleApproachingCauseCode(this.emergencyVehicleApproachingCauseCode);
        }

        @JsonCreator
        private EmergencyVehicleApproachingCauseCodeCase(JsonNode jsonNode) throws IOException {
            this.emergencyVehicleApproachingCauseCode = ApiHelper.deserialize(jsonNode,
                EmergencyVehicleApproachingCauseCode.class);
        }

        @Override
        public String toString() {
            return emergencyVehicleApproachingCauseCode.toString();
        }
    }

    /**
     * This is a custom deserializer class for CauseCodeChoice.
     */
    protected static class CauseCodeChoiceDeserializer
            extends JsonDeserializer<CauseCodeChoice> {

        @Override
        public CauseCodeChoice deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(TrafficConditionCauseCodeCase.class,
                    AccidentCauseCodeCase.class, RoadworksCauseCodeCase.class,
                    ImpassabilityCauseCodeCase.class, WrongWayDrivingCauseCodeCase.class,
                    EmergencyVehicleApproachingCauseCodeCase.class), true);
        }
    }

}
