/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.verizon.thingspace.ApiHelper;
import com.verizon.thingspace.models.AdvisoryContent;
import com.verizon.thingspace.models.ExitServiceContent;
import com.verizon.thingspace.models.GenericSignContent;
import com.verizon.thingspace.models.SpeedLimitContent;
import com.verizon.thingspace.models.WorkZoneContent;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = DataFrameContent.DataFrameContentDeserializer.class)
public abstract class DataFrameContent {
    
    /**
     * This is AdvisoryContent case.
     * @param advisoryContent AdvisoryContent value for advisoryContent.
     * @return The AdvisoryContentCase object.
     */
    public static DataFrameContent fromAdvisoryContent(AdvisoryContent advisoryContent) {
        return advisoryContent == null ? null : new AdvisoryContentCase(advisoryContent);
    }

    /**
     * This is WorkZoneContent case.
     * @param workZoneContent WorkZoneContent value for workZoneContent.
     * @return The WorkZoneContentCase object.
     */
    public static DataFrameContent fromWorkZoneContent(WorkZoneContent workZoneContent) {
        return workZoneContent == null ? null : new WorkZoneContentCase(workZoneContent);
    }

    /**
     * This is GenericSignContent case.
     * @param genericSignContent GenericSignContent value for genericSignContent.
     * @return The GenericSignContentCase object.
     */
    public static DataFrameContent fromGenericSignContent(GenericSignContent genericSignContent) {
        return genericSignContent == null ? null : new GenericSignContentCase(genericSignContent);
    }

    /**
     * This is SpeedLimitContent case.
     * @param speedLimitContent SpeedLimitContent value for speedLimitContent.
     * @return The SpeedLimitContentCase object.
     */
    public static DataFrameContent fromSpeedLimitContent(SpeedLimitContent speedLimitContent) {
        return speedLimitContent == null ? null : new SpeedLimitContentCase(speedLimitContent);
    }

    /**
     * This is ExitServiceContent case.
     * @param exitServiceContent ExitServiceContent value for exitServiceContent.
     * @return The ExitServiceContentCase object.
     */
    public static DataFrameContent fromExitServiceContent(ExitServiceContent exitServiceContent) {
        return exitServiceContent == null ? null : new ExitServiceContentCase(exitServiceContent);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R advisoryContent(AdvisoryContent advisoryContent);

        R workZoneContent(WorkZoneContent workZoneContent);

        R genericSignContent(GenericSignContent genericSignContent);

        R speedLimitContent(SpeedLimitContent speedLimitContent);

        R exitServiceContent(ExitServiceContent exitServiceContent);
    }

    /**
     * This is a implementation class for AdvisoryContentCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "AdvisoryContent")
    private static class AdvisoryContentCase extends DataFrameContent {

        @JsonValue
        private AdvisoryContent advisoryContent;

        AdvisoryContentCase(AdvisoryContent advisoryContent) {
            this.advisoryContent = advisoryContent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.advisoryContent(this.advisoryContent);
        }

        @JsonCreator
        private AdvisoryContentCase(JsonNode jsonNode) throws IOException {
            this.advisoryContent = ApiHelper.deserialize(jsonNode,
                AdvisoryContent.class);
        }

        @Override
        public String toString() {
            return advisoryContent.toString();
        }
    }

    /**
     * This is a implementation class for WorkZoneContentCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "WorkZoneContent")
    private static class WorkZoneContentCase extends DataFrameContent {

        @JsonValue
        private WorkZoneContent workZoneContent;

        WorkZoneContentCase(WorkZoneContent workZoneContent) {
            this.workZoneContent = workZoneContent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.workZoneContent(this.workZoneContent);
        }

        @JsonCreator
        private WorkZoneContentCase(JsonNode jsonNode) throws IOException {
            this.workZoneContent = ApiHelper.deserialize(jsonNode,
                WorkZoneContent.class);
        }

        @Override
        public String toString() {
            return workZoneContent.toString();
        }
    }

    /**
     * This is a implementation class for GenericSignContentCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "GenericSignContent")
    private static class GenericSignContentCase extends DataFrameContent {

        @JsonValue
        private GenericSignContent genericSignContent;

        GenericSignContentCase(GenericSignContent genericSignContent) {
            this.genericSignContent = genericSignContent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.genericSignContent(this.genericSignContent);
        }

        @JsonCreator
        private GenericSignContentCase(JsonNode jsonNode) throws IOException {
            this.genericSignContent = ApiHelper.deserialize(jsonNode,
                GenericSignContent.class);
        }

        @Override
        public String toString() {
            return genericSignContent.toString();
        }
    }

    /**
     * This is a implementation class for SpeedLimitContentCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "SpeedLimitContent")
    private static class SpeedLimitContentCase extends DataFrameContent {

        @JsonValue
        private SpeedLimitContent speedLimitContent;

        SpeedLimitContentCase(SpeedLimitContent speedLimitContent) {
            this.speedLimitContent = speedLimitContent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.speedLimitContent(this.speedLimitContent);
        }

        @JsonCreator
        private SpeedLimitContentCase(JsonNode jsonNode) throws IOException {
            this.speedLimitContent = ApiHelper.deserialize(jsonNode,
                SpeedLimitContent.class);
        }

        @Override
        public String toString() {
            return speedLimitContent.toString();
        }
    }

    /**
     * This is a implementation class for ExitServiceContentCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "ExitServiceContent")
    private static class ExitServiceContentCase extends DataFrameContent {

        @JsonValue
        private ExitServiceContent exitServiceContent;

        ExitServiceContentCase(ExitServiceContent exitServiceContent) {
            this.exitServiceContent = exitServiceContent;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.exitServiceContent(this.exitServiceContent);
        }

        @JsonCreator
        private ExitServiceContentCase(JsonNode jsonNode) throws IOException {
            this.exitServiceContent = ApiHelper.deserialize(jsonNode,
                ExitServiceContent.class);
        }

        @Override
        public String toString() {
            return exitServiceContent.toString();
        }
    }

    /**
     * This is a custom deserializer class for DataFrameContent.
     */
    protected static class DataFrameContentDeserializer
            extends JsonDeserializer<DataFrameContent> {

        @Override
        public DataFrameContent deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(AdvisoryContentCase.class,
                    WorkZoneContentCase.class, GenericSignContentCase.class,
                    SpeedLimitContentCase.class, ExitServiceContentCase.class), true);
        }
    }

}
