/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.verizon.thingspace.ApiHelper;
import com.verizon.thingspace.models.DevicesFilter;
import com.verizon.thingspace.models.PaginationFilter;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = DevicesRequestFilter.DevicesRequestFilterDeserializer.class)
public abstract class DevicesRequestFilter {
    
    /**
     * This is DevicesFilter case.
     * @param devicesFilter DevicesFilter value for devicesFilter.
     * @return The DevicesFilterCase object.
     */
    public static DevicesRequestFilter fromDevicesFilter(DevicesFilter devicesFilter) {
        return devicesFilter == null ? null : new DevicesFilterCase(devicesFilter);
    }

    /**
     * This is PaginationFilter case.
     * @param paginationFilter PaginationFilter value for paginationFilter.
     * @return The PaginationFilterCase object.
     */
    public static DevicesRequestFilter fromPaginationFilter(PaginationFilter paginationFilter) {
        return paginationFilter == null ? null : new PaginationFilterCase(paginationFilter);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R devicesFilter(DevicesFilter devicesFilter);

        R paginationFilter(PaginationFilter paginationFilter);
    }

    /**
     * This is a implementation class for DevicesFilterCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "DevicesFilter")
    private static class DevicesFilterCase extends DevicesRequestFilter {

        @JsonValue
        private DevicesFilter devicesFilter;

        DevicesFilterCase(DevicesFilter devicesFilter) {
            this.devicesFilter = devicesFilter;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.devicesFilter(this.devicesFilter);
        }

        @JsonCreator
        private DevicesFilterCase(JsonNode jsonNode) throws IOException {
            this.devicesFilter = ApiHelper.deserialize(jsonNode,
                DevicesFilter.class);
        }

        @Override
        public String toString() {
            return devicesFilter.toString();
        }
    }

    /**
     * This is a implementation class for PaginationFilterCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "PaginationFilter")
    private static class PaginationFilterCase extends DevicesRequestFilter {

        @JsonValue
        private PaginationFilter paginationFilter;

        PaginationFilterCase(PaginationFilter paginationFilter) {
            this.paginationFilter = paginationFilter;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.paginationFilter(this.paginationFilter);
        }

        @JsonCreator
        private PaginationFilterCase(JsonNode jsonNode) throws IOException {
            this.paginationFilter = ApiHelper.deserialize(jsonNode,
                PaginationFilter.class);
        }

        @Override
        public String toString() {
            return paginationFilter.toString();
        }
    }

    /**
     * This is a custom deserializer class for DevicesRequestFilter.
     */
    protected static class DevicesRequestFilterDeserializer
            extends JsonDeserializer<DevicesRequestFilter> {

        @Override
        public DevicesRequestFilter deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(DevicesFilterCase.class,
                    PaginationFilterCase.class), true);
        }
    }

}
