/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.verizon.thingspace.ApiHelper;
import com.verizon.thingspace.models.ETXMAPMessageGeoJSONPolygon;
import com.verizon.thingspace.models.ETXMAPMessageIntersectionCoordinates;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = MapDataQueryRequest.MapDataQueryRequestDeserializer.class)
public abstract class MapDataQueryRequest {
    
    /**
     * This is ETX MAP Message Intersection Coordinates case.
     * @param eTXMAPMessageIntersectionCoordinates ETXMAPMessageIntersectionCoordinates value for eTXMAPMessageIntersectionCoordinates.
     * @return The ETXMAPMessageIntersectionCoordinatesCase object.
     */
    public static MapDataQueryRequest fromETXMAPMessageIntersectionCoordinates(
            ETXMAPMessageIntersectionCoordinates eTXMAPMessageIntersectionCoordinates) {
        return eTXMAPMessageIntersectionCoordinates == null ? null : new ETXMAPMessageIntersectionCoordinatesCase(eTXMAPMessageIntersectionCoordinates);
    }

    /**
     * This is ETX MAP Message GeoJSON Polygon case.
     * @param eTXMAPMessageGeoJSONPolygon ETXMAPMessageGeoJSONPolygon value for eTXMAPMessageGeoJSONPolygon.
     * @return The ETXMAPMessageGeoJSONPolygonCase object.
     */
    public static MapDataQueryRequest fromETXMAPMessageGeoJSONPolygon(
            ETXMAPMessageGeoJSONPolygon eTXMAPMessageGeoJSONPolygon) {
        return eTXMAPMessageGeoJSONPolygon == null ? null : new ETXMAPMessageGeoJSONPolygonCase(eTXMAPMessageGeoJSONPolygon);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R eTXMAPMessageIntersectionCoordinates(ETXMAPMessageIntersectionCoordinates eTXMAPMessageIntersectionCoordinates);

        R eTXMAPMessageGeoJSONPolygon(ETXMAPMessageGeoJSONPolygon eTXMAPMessageGeoJSONPolygon);
    }

    /**
     * This is a implementation class for ETXMAPMessageIntersectionCoordinatesCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "ETXMAPMessageIntersectionCoordinates")
    private static class ETXMAPMessageIntersectionCoordinatesCase extends MapDataQueryRequest {

        @JsonValue
        private ETXMAPMessageIntersectionCoordinates eTXMAPMessageIntersectionCoordinates;

        ETXMAPMessageIntersectionCoordinatesCase(ETXMAPMessageIntersectionCoordinates eTXMAPMessageIntersectionCoordinates) {
            this.eTXMAPMessageIntersectionCoordinates = eTXMAPMessageIntersectionCoordinates;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.eTXMAPMessageIntersectionCoordinates(this.eTXMAPMessageIntersectionCoordinates);
        }

        @JsonCreator
        private ETXMAPMessageIntersectionCoordinatesCase(JsonNode jsonNode) throws IOException {
            this.eTXMAPMessageIntersectionCoordinates = ApiHelper.deserialize(jsonNode,
                ETXMAPMessageIntersectionCoordinates.class);
        }

        @Override
        public String toString() {
            return eTXMAPMessageIntersectionCoordinates.toString();
        }
    }

    /**
     * This is a implementation class for ETXMAPMessageGeoJSONPolygonCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "ETXMAPMessageGeoJSONPolygon")
    private static class ETXMAPMessageGeoJSONPolygonCase extends MapDataQueryRequest {

        @JsonValue
        private ETXMAPMessageGeoJSONPolygon eTXMAPMessageGeoJSONPolygon;

        ETXMAPMessageGeoJSONPolygonCase(ETXMAPMessageGeoJSONPolygon eTXMAPMessageGeoJSONPolygon) {
            this.eTXMAPMessageGeoJSONPolygon = eTXMAPMessageGeoJSONPolygon;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.eTXMAPMessageGeoJSONPolygon(this.eTXMAPMessageGeoJSONPolygon);
        }

        @JsonCreator
        private ETXMAPMessageGeoJSONPolygonCase(JsonNode jsonNode) throws IOException {
            this.eTXMAPMessageGeoJSONPolygon = ApiHelper.deserialize(jsonNode,
                ETXMAPMessageGeoJSONPolygon.class);
        }

        @Override
        public String toString() {
            return eTXMAPMessageGeoJSONPolygon.toString();
        }
    }

    /**
     * This is a custom deserializer class for MapDataQueryRequest.
     */
    protected static class MapDataQueryRequestDeserializer
            extends JsonDeserializer<MapDataQueryRequest> {

        @Override
        public MapDataQueryRequest deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(
                    ETXMAPMessageIntersectionCoordinatesCase.class,
                    ETXMAPMessageGeoJSONPolygonCase.class), true);
        }
    }

}
