/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.verizon.thingspace.ApiHelper;
import com.verizon.thingspace.models.ITISItemWrapper;
import com.verizon.thingspace.models.TextPhraseItemWrapper;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = TextPhraseOrITIS.TextPhraseOrITISDeserializer.class)
public abstract class TextPhraseOrITIS {
    
    /**
     * This is ITISItemWrapper case.
     * @param iTISItemWrapper ITISItemWrapper value for iTISItemWrapper.
     * @return The ITISItemWrapperCase object.
     */
    public static TextPhraseOrITIS fromITISItemWrapper(ITISItemWrapper iTISItemWrapper) {
        return iTISItemWrapper == null ? null : new ITISItemWrapperCase(iTISItemWrapper);
    }

    /**
     * This is TextPhraseItemWrapper case.
     * @param textPhraseItemWrapper TextPhraseItemWrapper value for textPhraseItemWrapper.
     * @return The TextPhraseItemWrapperCase object.
     */
    public static TextPhraseOrITIS fromTextPhraseItemWrapper(
            TextPhraseItemWrapper textPhraseItemWrapper) {
        return textPhraseItemWrapper == null ? null : new TextPhraseItemWrapperCase(textPhraseItemWrapper);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R iTISItemWrapper(ITISItemWrapper iTISItemWrapper);

        R textPhraseItemWrapper(TextPhraseItemWrapper textPhraseItemWrapper);
    }

    /**
     * This is a implementation class for ITISItemWrapperCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "ITISItemWrapper")
    private static class ITISItemWrapperCase extends TextPhraseOrITIS {

        @JsonValue
        private ITISItemWrapper iTISItemWrapper;

        ITISItemWrapperCase(ITISItemWrapper iTISItemWrapper) {
            this.iTISItemWrapper = iTISItemWrapper;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.iTISItemWrapper(this.iTISItemWrapper);
        }

        @JsonCreator
        private ITISItemWrapperCase(JsonNode jsonNode) throws IOException {
            this.iTISItemWrapper = ApiHelper.deserialize(jsonNode,
                ITISItemWrapper.class);
        }

        @Override
        public String toString() {
            return iTISItemWrapper.toString();
        }
    }

    /**
     * This is a implementation class for TextPhraseItemWrapperCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "TextPhraseItemWrapper")
    private static class TextPhraseItemWrapperCase extends TextPhraseOrITIS {

        @JsonValue
        private TextPhraseItemWrapper textPhraseItemWrapper;

        TextPhraseItemWrapperCase(TextPhraseItemWrapper textPhraseItemWrapper) {
            this.textPhraseItemWrapper = textPhraseItemWrapper;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.textPhraseItemWrapper(this.textPhraseItemWrapper);
        }

        @JsonCreator
        private TextPhraseItemWrapperCase(JsonNode jsonNode) throws IOException {
            this.textPhraseItemWrapper = ApiHelper.deserialize(jsonNode,
                TextPhraseItemWrapper.class);
        }

        @Override
        public String toString() {
            return textPhraseItemWrapper.toString();
        }
    }

    /**
     * This is a custom deserializer class for TextPhraseOrITIS.
     */
    protected static class TextPhraseOrITISDeserializer
            extends JsonDeserializer<TextPhraseOrITIS> {

        @Override
        public TextPhraseOrITIS deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(ITISItemWrapperCase.class,
                    TextPhraseItemWrapperCase.class), true);
        }
    }

}
